const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '../../..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const assert = (value, message) => { if (!value) throw new Error(message); };
const route = read('app/api/tournament-v2/setup/finalize/route.js');
const setupRoute = read('app/api/tournament-v2/setup/route.js');
const useCase = read('lib/tournament/setupFinalize.js');
const migration = read('database/migrations/095_unified_setup_finalize_v3.sql');
assert(route.includes('requireValidatedGroupAdmin'), 'finalize must require admin');
assert(route.includes("'finalize_internal_doubles_group_knockout_v3'"), 'finalize must use the v3 atomic finalizer RPC');
assert(useCase.includes('FINALIZE_NOT_ATOMIC'), 'finalize must expose atomic failure code');
assert(route.includes('p_group_id'), 'finalize must scope group');
assert(!route.includes('tournament_draw_slots'), 'finalize must not use draw slots');
assert(useCase.includes('IDEMPOTENCY_KEY_REUSED'), 'idempotency error must be stable');
assert(useCase.includes('REVISION_CONFLICT'), 'revision error must be stable');
assert(route.includes('previewFingerprint') && route.includes('p_preview_fingerprint'), 'finalize must bind to the persisted canonical draw');
assert(route.includes('error: error.message') && route.includes('code: error.code'), 'finalize must use the shared top-level error envelope');
assert(setupRoute.includes("action === 'replace_invited_clubs'"), 'existing friendly invite mutation remains available');
assert(setupRoute.includes('invitedClubs:'), 'setup GET must return invitedClubs for resume');
assert(migration.includes('finalize_internal_doubles_group_knockout_v2') && migration.includes('round_scoring') && migration.includes('memberIds'), 'v3 adapts aggregate member IDs, reuses the atomic materializer, and persists stage BO configuration');
console.log('unified setup finalize API contract ok');
