-- Migration: Add members table and transaction categorization
-- Created: 2026-01-17
-- Description: Adds club_members table and enhances quy_pickleball with categorization features

-- ============================================================
-- 1. CREATE CLUB_MEMBERS TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS club_members (
  id bigint generated by default as identity primary key,
  full_name text unique not null,
  aliases text[], -- Tên khác, biệt danh
  phone text,
  email text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Tắt RLS cho admin (có thể bật sau nếu cần bảo mật)
ALTER TABLE club_members DISABLE ROW LEVEL SECURITY;

-- Create index for fuzzy search
CREATE INDEX IF NOT EXISTS idx_members_full_name ON club_members(full_name);

-- ============================================================
-- 2. INSERT INITIAL MEMBER DATA WITH ALIASES (KEYWORDS)
-- ============================================================
-- Note: Aliases are keywords for reverse lookup matching
-- Format: Full name should be normalized, aliases can include variations

INSERT INTO club_members (full_name, aliases) VALUES
('ĐỖ ĐỨC TÚ', ARRAY['DO DUC TU', 'DUC TU', 'DD TU']),
('ĐẶNG TIẾN ANH', ARRAY['DANG TIEN ANH', 'TIEN ANH', 'DT ANH', 'NHAT ANH', 'DANG TRAN NHAT ANH']),
('VŨ DUY TÙNG', ARRAY['VU DUY TUNG', 'DUY TUNG', 'VD TUNG']),
('ĐẶNG NGỌC DƯƠNG', ARRAY['DANG NGOC DUONG', 'NGOC DUONG', 'DN DUONG']),
('NGUYỄN CHƯƠNG LONG', ARRAY['NGUYEN CHUONG LONG', 'CHUONG LONG', 'NC LONG']),
('ĐỒNG MẠNH LINH', ARRAY['DONG MANH LINH', 'MANH LINH', 'DM LINH']),
('TRẦN TẤT HẢO', ARRAY['TRAN TAT HAO', 'TAT HAO', 'TT HAO']),
('HOÀNG NGỌC THẠCH', ARRAY['HOANG NGOC THACH', 'NGOC THACH', 'HN THACH']),
('NGUYỄN NHẬT QUANG', ARRAY['NGUYEN NHAT QUANG', 'NHAT QUANG', 'NN QUANG']),
('VŨ NGỌC HƯNG', ARRAY['VU NGOC HUNG', 'NGOC HUNG', 'VN HUNG']),
('NGUYỄN VĂN THÀNH', ARRAY['NGUYEN VAN THANH', 'VAN THANH', 'NV THANH']),
('NGUYỄN MẠNH THẮNG', ARRAY['NGUYEN MANH THANG', 'MANH THANG', 'NM THANG']),
('LẠI HỮU PHƯƠNG', ARRAY['LAI HUU PHUONG', 'HUU PHUONG', 'LH PHUONG']),
('TRẦN TUẤN TÚ', ARRAY['TRAN TUAN TU', 'TUAN TU', 'TT TU', 'TUAN'])
ON CONFLICT (full_name) DO UPDATE SET aliases = EXCLUDED.aliases;

-- ============================================================
-- 3. UPDATE QUY_PICKLEBALL TABLE - ADD NEW COLUMNS
-- ============================================================

-- Add confidence and parsing metadata columns
ALTER TABLE quy_pickleball 
ADD COLUMN IF NOT EXISTS confidence_score numeric DEFAULT 100;

ALTER TABLE quy_pickleball 
ADD COLUMN IF NOT EXISTS bank_detected text;

ALTER TABLE quy_pickleball 
ADD COLUMN IF NOT EXISTS parsing_method text DEFAULT 'unknown';

-- Add transaction categorization columns
ALTER TABLE quy_pickleball 
ADD COLUMN IF NOT EXISTS loai_giao_dich text DEFAULT 'khac';

ALTER TABLE quy_pickleball 
ADD COLUMN IF NOT EXISTS huong_giao_dich text DEFAULT 'in';

ALTER TABLE quy_pickleball 
ADD COLUMN IF NOT EXISTS is_manually_categorized boolean DEFAULT false;

ALTER TABLE quy_pickleball 
ADD COLUMN IF NOT EXISTS admin_note text;

-- ============================================================
-- 4. ADD CONSTRAINTS
-- ============================================================

-- Add check constraints for valid values
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'quy_pickleball_loai_giao_dich_check'
  ) THEN
    ALTER TABLE quy_pickleball 
    ADD CONSTRAINT quy_pickleball_loai_giao_dich_check 
    CHECK (loai_giao_dich IN ('nop_phat', 'nop_quy', 'khac'));
  END IF;
END $$;

DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'quy_pickleball_huong_giao_dich_check'
  ) THEN
    ALTER TABLE quy_pickleball 
    ADD CONSTRAINT quy_pickleball_huong_giao_dich_check 
    CHECK (huong_giao_dich IN ('in', 'out'));
  END IF;
END $$;

-- ============================================================
-- 5. CREATE INDEXES FOR PERFORMANCE
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_loai_giao_dich ON quy_pickleball(loai_giao_dich);
CREATE INDEX IF NOT EXISTS idx_huong_giao_dich ON quy_pickleball(huong_giao_dich);
CREATE INDEX IF NOT EXISTS idx_confidence_score ON quy_pickleball(confidence_score);
CREATE INDEX IF NOT EXISTS idx_is_manually_categorized ON quy_pickleball(is_manually_categorized);
CREATE INDEX IF NOT EXISTS idx_nguoi_nop ON quy_pickleball(nguoi_nop);

-- ============================================================
-- 6. COMMENTS FOR DOCUMENTATION
-- ============================================================

COMMENT ON TABLE club_members IS 'Danh sách thành viên câu lạc bộ Pickleball';
COMMENT ON COLUMN club_members.full_name IS 'Tên đầy đủ thành viên (uppercase)';
COMMENT ON COLUMN club_members.aliases IS 'Các tên khác, biệt danh của thành viên';

COMMENT ON COLUMN quy_pickleball.confidence_score IS 'Độ tin cậy của việc parse tên (0-100)';
COMMENT ON COLUMN quy_pickleball.bank_detected IS 'Ngân hàng phát hiện từ nội dung (BIDV, MB, VCB...)';
COMMENT ON COLUMN quy_pickleball.parsing_method IS 'Phương pháp parse: pkb, pattern, fuzzy, fallback';
COMMENT ON COLUMN quy_pickleball.loai_giao_dich IS 'Loại giao dịch: nop_phat (nộp phạt), nop_quy (nộp quỹ), khac (khác)';
COMMENT ON COLUMN quy_pickleball.huong_giao_dich IS 'Hướng giao dịch: in (tiền vào), out (tiền ra)';
COMMENT ON COLUMN quy_pickleball.is_manually_categorized IS 'Admin đã categorize thủ công?';
COMMENT ON COLUMN quy_pickleball.admin_note IS 'Ghi chú của admin';

-- ============================================================
-- MIGRATION COMPLETE
-- ============================================================
