-- Migration: Add ranking_snapshots table for leaderboard history
-- Created: 2026-01-20
-- Description: Stores daily snapshots of member rankings to track rank changes over time

-- ============================================================
-- 1. CREATE RANKING_SNAPSHOTS TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS ranking_snapshots (
  id bigint generated by default as identity primary key,
  nguoi_nop text not null,
  rank_position integer not null,
  total_amount numeric not null,
  snapshot_date date not null,
  created_at timestamp with time zone default now()
);

-- Tắt RLS cho admin
ALTER TABLE ranking_snapshots DISABLE ROW LEVEL SECURITY;

-- ============================================================
-- 2. CREATE INDEXES FOR PERFORMANCE
-- ============================================================

-- Index for querying by member name
CREATE INDEX IF NOT EXISTS idx_snapshots_nguoi_nop 
ON ranking_snapshots(nguoi_nop);

-- Index for querying by date (most common query)
CREATE INDEX IF NOT EXISTS idx_snapshots_date 
ON ranking_snapshots(snapshot_date DESC);

-- Composite index for efficient lookups
CREATE INDEX IF NOT EXISTS idx_snapshots_date_nguoi_nop 
ON ranking_snapshots(snapshot_date DESC, nguoi_nop);

-- ============================================================
-- 3. ADD CONSTRAINTS
-- ============================================================

-- Ensure unique snapshot per member per date
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'ranking_snapshots_unique_member_date'
  ) THEN
    ALTER TABLE ranking_snapshots 
    ADD CONSTRAINT ranking_snapshots_unique_member_date 
    UNIQUE (nguoi_nop, snapshot_date);
  END IF;
END $$;

-- Ensure rank_position is positive
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'ranking_snapshots_rank_positive'
  ) THEN
    ALTER TABLE ranking_snapshots 
    ADD CONSTRAINT ranking_snapshots_rank_positive 
    CHECK (rank_position > 0);
  END IF;
END $$;

-- ============================================================
-- 4. COMMENTS FOR DOCUMENTATION
-- ============================================================

COMMENT ON TABLE ranking_snapshots IS 'Lưu trữ snapshot xếp hạng hàng ngày để theo dõi thay đổi';
COMMENT ON COLUMN ranking_snapshots.nguoi_nop IS 'Tên thành viên (phải khớp với quy_pickleball.nguoi_nop)';
COMMENT ON COLUMN ranking_snapshots.rank_position IS 'Vị trí xếp hạng (1 = cao nhất)';
COMMENT ON COLUMN ranking_snapshots.total_amount IS 'Tổng số tiền đóng góp tại thời điểm snapshot';
COMMENT ON COLUMN ranking_snapshots.snapshot_date IS 'Ngày snapshot (không bao gồm giờ)';
COMMENT ON COLUMN ranking_snapshots.created_at IS 'Thời gian tạo snapshot';

-- ============================================================
-- MIGRATION COMPLETE
-- ============================================================
