-- Migration 007: Multi-group Phase 1
-- Adds group tenancy while keeping the current CLB data under a default group.

CREATE TABLE IF NOT EXISTS groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code text NOT NULL UNIQUE,
    name text NOT NULL,
    description text,
    admin_password_hash text NOT NULL,
    member_password_hash text NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    CONSTRAINT groups_code_length CHECK (char_length(code) = 8)
);

ALTER TABLE groups DISABLE ROW LEVEL SECURITY;

INSERT INTO groups (
    id,
    code,
    name,
    description,
    admin_password_hash,
    member_password_hash
)
VALUES (
    1,
    'P246CLUB',
    'Pickleball 246 Club',
    'Nhóm mặc định cho dữ liệu CLB hiện tại',
    'legacy-auth-disabled',
    'legacy-auth-disabled'
)
ON CONFLICT (id) DO UPDATE SET
    code = EXCLUDED.code,
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    updated_at = now();

SELECT setval(pg_get_serial_sequence('groups', 'id'), GREATEST((SELECT MAX(id) FROM groups), 1), true);

ALTER TABLE club_members
    ADD COLUMN IF NOT EXISTS group_id bigint REFERENCES groups(id) DEFAULT 1;

ALTER TABLE quy_pickleball
    ADD COLUMN IF NOT EXISTS group_id bigint REFERENCES groups(id) DEFAULT 1;

ALTER TABLE fund_events
    ADD COLUMN IF NOT EXISTS group_id bigint REFERENCES groups(id) DEFAULT 1;

ALTER TABLE tournaments
    ADD COLUMN IF NOT EXISTS group_id bigint REFERENCES groups(id) DEFAULT 1;

ALTER TABLE tournament_teams
    ADD COLUMN IF NOT EXISTS group_id bigint REFERENCES groups(id) DEFAULT 1;

ALTER TABLE tournament_players
    ADD COLUMN IF NOT EXISTS group_id bigint REFERENCES groups(id) DEFAULT 1;

ALTER TABLE tournament_pairings
    ADD COLUMN IF NOT EXISTS group_id bigint REFERENCES groups(id) DEFAULT 1;

ALTER TABLE tournament_matches
    ADD COLUMN IF NOT EXISTS group_id bigint REFERENCES groups(id) DEFAULT 1;

ALTER TABLE tournament_settings
    ADD COLUMN IF NOT EXISTS group_id bigint REFERENCES groups(id) DEFAULT 1;

UPDATE club_members SET group_id = 1 WHERE group_id IS NULL;
UPDATE quy_pickleball SET group_id = 1 WHERE group_id IS NULL;
UPDATE fund_events SET group_id = 1 WHERE group_id IS NULL;
UPDATE tournaments SET group_id = 1 WHERE group_id IS NULL;
UPDATE tournament_teams SET group_id = 1 WHERE group_id IS NULL;
UPDATE tournament_players SET group_id = 1 WHERE group_id IS NULL;
UPDATE tournament_pairings SET group_id = 1 WHERE group_id IS NULL;
UPDATE tournament_matches SET group_id = 1 WHERE group_id IS NULL;
UPDATE tournament_settings SET group_id = 1 WHERE group_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_club_members_group_id ON club_members(group_id);
CREATE INDEX IF NOT EXISTS idx_quy_pickleball_group_id ON quy_pickleball(group_id);
CREATE INDEX IF NOT EXISTS idx_fund_events_group_id ON fund_events(group_id);
CREATE INDEX IF NOT EXISTS idx_tournaments_group_id ON tournaments(group_id);
CREATE INDEX IF NOT EXISTS idx_tournament_teams_group_id ON tournament_teams(group_id);
CREATE INDEX IF NOT EXISTS idx_tournament_players_group_id ON tournament_players(group_id);
CREATE INDEX IF NOT EXISTS idx_tournament_pairings_group_id ON tournament_pairings(group_id);
CREATE INDEX IF NOT EXISTS idx_tournament_matches_group_id ON tournament_matches(group_id);
CREATE INDEX IF NOT EXISTS idx_tournament_settings_group_id ON tournament_settings(group_id);

DO $$
DECLARE
    settings_unique_constraint text;
BEGIN
    SELECT con.conname
    INTO settings_unique_constraint
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE nsp.nspname = current_schema()
      AND rel.relname = 'tournament_settings'
      AND con.contype = 'u'
      AND (
          SELECT array_agg(att.attname ORDER BY ord.ordinality)
          FROM unnest(con.conkey) WITH ORDINALITY AS ord(attnum, ordinality)
          JOIN pg_attribute att ON att.attrelid = con.conrelid AND att.attnum = ord.attnum
      ) = ARRAY['tournament_id', 'setting_key'];

    IF settings_unique_constraint IS NOT NULL THEN
        EXECUTE format('ALTER TABLE tournament_settings DROP CONSTRAINT %I', settings_unique_constraint);
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_tournament_settings_group_tournament_key
    ON tournament_settings(group_id, tournament_id, setting_key);

COMMENT ON TABLE groups IS 'Danh sách nhóm/CLB dùng chung ứng dụng TeamFund';
COMMENT ON COLUMN groups.code IS 'Mã nhóm 8 ký tự để thành viên tham gia';
COMMENT ON COLUMN groups.admin_password_hash IS 'Hash mật khẩu quản trị nhóm';
COMMENT ON COLUMN groups.member_password_hash IS 'Hash mật khẩu thành viên nhóm';
