-- database/migrations/015_tournament_module_v2.sql
-- Module giải đấu v2 (clean-slate). Drop bảng giải cũ, tạo mô hình stage 2 trục.
-- ÁP TAY trên Supabase. User đồng ý mất dữ liệu giải cũ.

DROP TABLE IF EXISTS tournament_matches CASCADE;
DROP TABLE IF EXISTS tournament_pairings CASCADE;
DROP TABLE IF EXISTS tournament_players CASCADE;
DROP TABLE IF EXISTS tournament_settings CASCADE;
DROP TABLE IF EXISTS tournament_teams CASCADE;
DROP TABLE IF EXISTS tournaments CASCADE;

CREATE TABLE IF NOT EXISTS tournaments (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id      bigint NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  name          text NOT NULL,
  description   text,
  location      text,
  event_date    date,
  status        text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','completed')),
  entrant_type  text NOT NULL DEFAULT 'pair' CHECK (entrant_type IN ('pair','team')),
  public_slug   text,
  settings      jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tournaments_group_slug ON tournaments(group_id, public_slug);
ALTER TABLE tournaments DISABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS tournament_stages (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id        bigint NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  tournament_id   bigint NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
  stage_order     integer NOT NULL DEFAULT 1,
  name            text NOT NULL,
  schedule_format text NOT NULL CHECK (schedule_format IN ('round_robin','knockout')),
  match_format    text NOT NULL DEFAULT 'simple' CHECK (match_format IN ('simple','mlp')),
  status          text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','active','completed')),
  config          jsonb NOT NULL DEFAULT '{}'::jsonb
);
ALTER TABLE tournament_stages DISABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS tournament_entrants (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id      bigint NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  tournament_id bigint NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
  name          text NOT NULL,
  seed          integer,
  color         text
);
ALTER TABLE tournament_entrants DISABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS tournament_entrant_members (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id     bigint NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  entrant_id   bigint NOT NULL REFERENCES tournament_entrants(id) ON DELETE CASCADE,
  member_id    bigint,
  display_name text,
  gender       text CHECK (gender IN ('m','f'))
);
ALTER TABLE tournament_entrant_members DISABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS tournament_stage_entrants (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id      bigint NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  stage_id      bigint NOT NULL REFERENCES tournament_stages(id) ON DELETE CASCADE,
  entrant_id    bigint NOT NULL REFERENCES tournament_entrants(id) ON DELETE CASCADE,
  group_label   text,
  seed_in_stage integer
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_stage_entrants_unique ON tournament_stage_entrants(group_id, stage_id, entrant_id);
ALTER TABLE tournament_stage_entrants DISABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS tournament_matches (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id          bigint NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  stage_id          bigint NOT NULL REFERENCES tournament_stages(id) ON DELETE CASCADE,
  round             integer NOT NULL DEFAULT 1,
  bracket_slot      integer,
  group_label       text,
  court             text,
  match_order       integer,
  entrant_a_id      bigint REFERENCES tournament_entrants(id) ON DELETE SET NULL,
  entrant_b_id      bigint REFERENCES tournament_entrants(id) ON DELETE SET NULL,
  status            text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','live','done')),
  winner_entrant_id bigint REFERENCES tournament_entrants(id) ON DELETE SET NULL,
  parent_match_id   bigint REFERENCES tournament_matches(id) ON DELETE SET NULL
);
ALTER TABLE tournament_matches DISABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS tournament_games (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id          bigint NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  match_id          bigint NOT NULL REFERENCES tournament_matches(id) ON DELETE CASCADE,
  game_no           integer NOT NULL DEFAULT 1,
  kind              text NOT NULL DEFAULT 'game'
                      CHECK (kind IN ('game','womens','mens','mixed1','mixed2','dreambreaker')),
  score_a           integer NOT NULL DEFAULT 0,
  score_b           integer NOT NULL DEFAULT 0,
  winner_entrant_id bigint REFERENCES tournament_entrants(id) ON DELETE SET NULL,
  lineup            jsonb NOT NULL DEFAULT '{}'::jsonb
);
ALTER TABLE tournament_games DISABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_tournament_stages_group_tournament ON tournament_stages(group_id, tournament_id);
CREATE INDEX IF NOT EXISTS idx_tournament_matches_group_stage ON tournament_matches(group_id, stage_id);

COMMENT ON TABLE tournaments IS 'Giải đấu (module v2, mô hình stage 2 trục)';
COMMENT ON COLUMN tournament_stages.schedule_format IS 'Trục xếp lịch: round_robin, knockout';
COMMENT ON COLUMN tournament_stages.match_format IS 'Trục tính trận: simple (best-of-N), mlp (ván con)';
