-- PickHub Phase 2: athlete identity, club memberships and revocable club sessions.
-- Apply after 027_index_member_origin_fk.sql. The legacy club_members model stays
-- writable during this compatibility window; no account/profile row is required.

BEGIN;

ALTER TABLE public.groups
  ADD COLUMN IF NOT EXISTS access_version bigint NOT NULL DEFAULT 1;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.groups'::regclass
      AND conname = 'groups_access_version_positive'
  ) THEN
    ALTER TABLE public.groups
      ADD CONSTRAINT groups_access_version_positive CHECK (access_version > 0);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.athletes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name text NOT NULL CHECK (btrim(display_name) <> ''),
  normalized_name text NOT NULL CHECK (btrim(normalized_name) <> ''),
  status text NOT NULL DEFAULT 'unclaimed'
    CHECK (status IN ('unclaimed', 'linked', 'merged', 'restricted', 'deleted')),
  merged_into_athlete_id bigint REFERENCES public.athletes(id) ON DELETE RESTRICT,
  legacy_club_member_id bigint UNIQUE REFERENCES public.club_members(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (
    (status = 'merged' AND merged_into_athlete_id IS NOT NULL)
    OR (status <> 'merged' AND merged_into_athlete_id IS NULL)
  ),
  CHECK (merged_into_athlete_id IS NULL OR merged_into_athlete_id <> id)
);

CREATE TABLE IF NOT EXISTS public.club_memberships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE RESTRICT,
  athlete_id bigint NOT NULL REFERENCES public.athletes(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive', 'suspended', 'ended')),
  effective_from date NOT NULL DEFAULT current_date,
  effective_to date,
  joined_on date,
  left_on date,
  club_alias text,
  primary_for_athlete boolean NOT NULL DEFAULT false,
  private_notes text,
  version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (effective_to IS NULL OR effective_to > effective_from),
  CHECK (left_on IS NULL OR joined_on IS NULL OR left_on >= joined_on),
  UNIQUE NULLS NOT DISTINCT (club_id, athlete_id, effective_to)
);

-- PostgreSQL requires this key to exist before the assessment composite FK is
-- declared. The primary key on id remains the row identity.
CREATE UNIQUE INDEX IF NOT EXISTS club_memberships_id_club_athlete_key
  ON public.club_memberships(id, club_id, athlete_id);

-- A dedicated map keeps every legacy identifier traceable without making the
-- old row the long-term athlete identity.
CREATE TABLE IF NOT EXISTS public.club_member_athlete_map (
  legacy_club_member_id bigint NOT NULL UNIQUE,
  club_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE RESTRICT,
  athlete_id bigint NOT NULL REFERENCES public.athletes(id) ON DELETE RESTRICT,
  club_membership_id bigint NOT NULL UNIQUE
    REFERENCES public.club_memberships(id) ON DELETE RESTRICT,
  migrated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (legacy_club_member_id),
  CONSTRAINT club_member_athlete_map_legacy_fk
    FOREIGN KEY (legacy_club_member_id, club_id)
    REFERENCES public.club_members(id, group_id)
    ON DELETE RESTRICT,
  CONSTRAINT club_member_athlete_map_membership_fk
    FOREIGN KEY (club_membership_id, club_id, athlete_id)
    REFERENCES public.club_memberships(id, club_id, athlete_id)
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.membership_assessments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE RESTRICT,
  club_membership_id bigint NOT NULL,
  athlete_id bigint NOT NULL REFERENCES public.athletes(id) ON DELETE RESTRICT,
  assessed_at timestamptz NOT NULL DEFAULT now(),
  effective_from date NOT NULL DEFAULT current_date,
  skill_level numeric(4, 2) CHECK (skill_level >= 0 AND skill_level <= 10),
  source text NOT NULL DEFAULT 'club_admin'
    CHECK (source IN ('club_admin', 'verified_match', 'import', 'correction')),
  notes text,
  actor_type text NOT NULL DEFAULT 'club_admin_session'
    CHECK (actor_type IN ('club_admin_session', 'platform_admin', 'system')),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT membership_assessments_membership_fk
    FOREIGN KEY (club_membership_id, club_id, athlete_id)
    REFERENCES public.club_memberships(id, club_id, athlete_id)
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.group_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  group_code text NOT NULL,
  role text NOT NULL CHECK (role IN ('member', 'admin')),
  session_key_hash text NOT NULL UNIQUE CHECK (btrim(session_key_hash) <> ''),
  issued_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  session_version bigint NOT NULL CHECK (session_version > 0),
  revoked_at timestamptz,
  revoke_reason text,
  last_seen_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (expires_at > issued_at),
  CHECK (revoked_at IS NULL OR revoked_at >= issued_at)
);

CREATE INDEX IF NOT EXISTS idx_athletes_normalized_name
  ON public.athletes(normalized_name) WHERE status NOT IN ('deleted', 'merged');
CREATE INDEX IF NOT EXISTS idx_athletes_merged_into
  ON public.athletes(merged_into_athlete_id) WHERE merged_into_athlete_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_club_memberships_club_effective
  ON public.club_memberships(club_id, status, effective_from, effective_to);
CREATE INDEX IF NOT EXISTS idx_club_memberships_athlete
  ON public.club_memberships(athlete_id, effective_from DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_club_memberships_one_primary
  ON public.club_memberships(athlete_id)
  WHERE primary_for_athlete AND status = 'active' AND effective_to IS NULL;
CREATE INDEX IF NOT EXISTS idx_club_member_athlete_map_athlete
  ON public.club_member_athlete_map(athlete_id);
CREATE INDEX IF NOT EXISTS idx_club_member_athlete_map_club
  ON public.club_member_athlete_map(club_id);
CREATE INDEX IF NOT EXISTS idx_club_member_athlete_map_membership
  ON public.club_member_athlete_map(club_membership_id);
CREATE INDEX IF NOT EXISTS idx_membership_assessments_membership_effective
  ON public.membership_assessments(club_membership_id, effective_from DESC, assessed_at DESC);
CREATE INDEX IF NOT EXISTS idx_membership_assessments_club_athlete
  ON public.membership_assessments(club_id, athlete_id, assessed_at DESC);
CREATE INDEX IF NOT EXISTS idx_membership_assessments_athlete
  ON public.membership_assessments(athlete_id);
CREATE INDEX IF NOT EXISTS idx_group_sessions_group_state
  ON public.group_sessions(group_id, session_version, expires_at)
  WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_group_sessions_expiry
  ON public.group_sessions(expires_at);

-- One athlete and one membership per legacy member. IDs are intentionally
-- reused only for the initial backfill, which makes the migration deterministic
-- while the separate mapping remains the compatibility contract.
INSERT INTO public.athletes (
  id,
  display_name,
  normalized_name,
  status,
  legacy_club_member_id,
  created_at,
  updated_at
)
SELECT
  member.id,
  btrim(member.full_name),
  lower(regexp_replace(btrim(member.full_name), '\s+', ' ', 'g')),
  'unclaimed',
  member.id,
  COALESCE(member.created_at, now()),
  COALESCE(member.updated_at, member.created_at, now())
FROM public.club_members AS member
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.club_memberships (
  id,
  club_id,
  athlete_id,
  status,
  effective_from,
  joined_on,
  club_alias,
  primary_for_athlete,
  created_at,
  updated_at
)
SELECT
  member.id,
  member.group_id,
  athlete.id,
  CASE WHEN member.is_active THEN 'active' ELSE 'inactive' END,
  COALESCE(member.created_at::date, current_date),
  member.created_at::date,
  btrim(member.full_name),
  true,
  COALESCE(member.created_at, now()),
  COALESCE(member.updated_at, member.created_at, now())
FROM public.club_members AS member
JOIN public.athletes AS athlete ON athlete.legacy_club_member_id = member.id
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.club_member_athlete_map (
  legacy_club_member_id,
  club_id,
  athlete_id,
  club_membership_id
)
SELECT member.id, member.group_id, athlete.id, membership.id
FROM public.club_members AS member
JOIN public.athletes AS athlete ON athlete.legacy_club_member_id = member.id
JOIN public.club_memberships AS membership
  ON membership.id = member.id
 AND membership.club_id = member.group_id
 AND membership.athlete_id = athlete.id
ON CONFLICT (legacy_club_member_id) DO NOTHING;

DO $$
DECLARE
  legacy_count bigint;
  mapping_count bigint;
  distinct_athlete_count bigint;
  distinct_membership_count bigint;
BEGIN
  SELECT count(*) INTO legacy_count FROM public.club_members;
  SELECT count(*), count(DISTINCT athlete_id), count(DISTINCT club_membership_id)
    INTO mapping_count, distinct_athlete_count, distinct_membership_count
  FROM public.club_member_athlete_map;

  IF mapping_count <> legacy_count
     OR distinct_athlete_count <> legacy_count
     OR distinct_membership_count <> legacy_count THEN
    RAISE EXCEPTION
      'Phase 2 identity backfill mismatch: legacy %, mappings %, athletes %, memberships %',
      legacy_count, mapping_count, distinct_athlete_count, distinct_membership_count;
  END IF;
END $$;

SELECT setval(
  pg_get_serial_sequence('public.athletes', 'id'),
  GREATEST(COALESCE((SELECT max(id) FROM public.athletes), 1), 1),
  true
);
SELECT setval(
  pg_get_serial_sequence('public.club_memberships', 'id'),
  GREATEST(COALESCE((SELECT max(id) FROM public.club_memberships), 1), 1),
  true
);

-- Compatibility columns let old and new repositories coexist. They are
-- nullable because tournament guests and newly created, non-legacy athletes
-- legitimately have no club_members row.
ALTER TABLE public.fund_event_participants
  ADD COLUMN IF NOT EXISTS athlete_id bigint REFERENCES public.athletes(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS club_membership_id bigint REFERENCES public.club_memberships(id) ON DELETE RESTRICT;

ALTER TABLE public.tournament_entrant_members
  ADD COLUMN IF NOT EXISTS athlete_id bigint REFERENCES public.athletes(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS club_membership_id bigint REFERENCES public.club_memberships(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS membership_club_id bigint REFERENCES public.groups(id) ON DELETE RESTRICT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.fund_event_participants'::regclass
      AND conname = 'fund_event_participants_identity_fk'
  ) THEN
    ALTER TABLE public.fund_event_participants
      ADD CONSTRAINT fund_event_participants_identity_fk
      FOREIGN KEY (club_membership_id, group_id, athlete_id)
      REFERENCES public.club_memberships(id, club_id, athlete_id)
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.tournament_entrant_members'::regclass
      AND conname = 'tournament_entrant_members_identity_fk'
  ) THEN
    ALTER TABLE public.tournament_entrant_members
      ADD CONSTRAINT tournament_entrant_members_identity_fk
      FOREIGN KEY (club_membership_id, membership_club_id, athlete_id)
      REFERENCES public.club_memberships(id, club_id, athlete_id)
      ON DELETE RESTRICT;
  END IF;
END $$;

UPDATE public.fund_event_participants AS participant
SET athlete_id = identity_map.athlete_id,
    club_membership_id = identity_map.club_membership_id
FROM public.club_member_athlete_map AS identity_map
WHERE participant.member_id = identity_map.legacy_club_member_id
  AND (participant.athlete_id IS NULL OR participant.club_membership_id IS NULL);

UPDATE public.tournament_entrant_members AS entrant_member
SET athlete_id = identity_map.athlete_id,
    club_membership_id = identity_map.club_membership_id,
    membership_club_id = membership.club_id
FROM public.club_member_athlete_map AS identity_map
JOIN public.club_memberships AS membership ON membership.id = identity_map.club_membership_id
WHERE entrant_member.member_id = identity_map.legacy_club_member_id
  AND (
    entrant_member.athlete_id IS NULL
    OR entrant_member.club_membership_id IS NULL
    OR entrant_member.membership_club_id IS NULL
  );

CREATE INDEX IF NOT EXISTS idx_fund_event_participants_identity
  ON public.fund_event_participants(club_membership_id, group_id, athlete_id);
CREATE INDEX IF NOT EXISTS idx_fund_event_participants_athlete
  ON public.fund_event_participants(athlete_id) WHERE athlete_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tournament_entrant_members_identity
  ON public.tournament_entrant_members(club_membership_id, membership_club_id, athlete_id);
CREATE INDEX IF NOT EXISTS idx_tournament_entrant_members_athlete
  ON public.tournament_entrant_members(athlete_id) WHERE athlete_id IS NOT NULL;

-- Synchronize a legacy member reference to its Phase 2 identity. New athletes
-- without a legacy row keep member_id NULL; callers must use the new columns.
CREATE OR REPLACE FUNCTION public.sync_phase2_identity_compatibility()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  mapped record;
  membership record;
BEGIN
  IF NEW.member_id IS NOT NULL THEN
    SELECT identity_map.athlete_id,
           identity_map.club_membership_id,
           club_membership.club_id
      INTO mapped
    FROM public.club_member_athlete_map AS identity_map
    JOIN public.club_memberships AS club_membership
      ON club_membership.id = identity_map.club_membership_id
    WHERE identity_map.legacy_club_member_id = NEW.member_id;

    IF mapped.club_membership_id IS NULL THEN
      RAISE EXCEPTION 'No Phase 2 identity mapping for legacy member %', NEW.member_id;
    END IF;
    IF NEW.athlete_id IS NOT NULL AND NEW.athlete_id <> mapped.athlete_id THEN
      RAISE EXCEPTION 'athlete_id conflicts with legacy member %', NEW.member_id;
    END IF;
    IF NEW.club_membership_id IS NOT NULL
       AND NEW.club_membership_id <> mapped.club_membership_id THEN
      RAISE EXCEPTION 'club_membership_id conflicts with legacy member %', NEW.member_id;
    END IF;

    NEW.athlete_id := mapped.athlete_id;
    NEW.club_membership_id := mapped.club_membership_id;
    IF TG_TABLE_NAME = 'tournament_entrant_members' THEN
      NEW.membership_club_id := mapped.club_id;
    ELSIF NEW.group_id <> mapped.club_id THEN
      RAISE EXCEPTION 'membership club % conflicts with participant group %', mapped.club_id, NEW.group_id;
    END IF;
  ELSIF NEW.club_membership_id IS NOT NULL THEN
    SELECT id, club_id, athlete_id INTO membership
    FROM public.club_memberships
    WHERE id = NEW.club_membership_id;

    IF membership.id IS NULL THEN
      RAISE EXCEPTION 'Unknown club membership %', NEW.club_membership_id;
    END IF;
    IF NEW.athlete_id IS NOT NULL AND NEW.athlete_id <> membership.athlete_id THEN
      RAISE EXCEPTION 'athlete_id conflicts with club membership %', NEW.club_membership_id;
    END IF;
    NEW.athlete_id := membership.athlete_id;

    IF TG_TABLE_NAME = 'tournament_entrant_members' THEN
      NEW.membership_club_id := membership.club_id;
    ELSIF NEW.group_id <> membership.club_id THEN
      RAISE EXCEPTION 'membership club % conflicts with participant group %', membership.club_id, NEW.group_id;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS fund_event_participants_sync_phase2_identity
  ON public.fund_event_participants;
CREATE TRIGGER fund_event_participants_sync_phase2_identity
BEFORE INSERT OR UPDATE OF member_id, athlete_id, club_membership_id, group_id
ON public.fund_event_participants
FOR EACH ROW EXECUTE FUNCTION public.sync_phase2_identity_compatibility();

DROP TRIGGER IF EXISTS tournament_entrant_members_sync_phase2_identity
  ON public.tournament_entrant_members;
CREATE TRIGGER tournament_entrant_members_sync_phase2_identity
BEFORE INSERT OR UPDATE OF member_id, athlete_id, club_membership_id, membership_club_id
ON public.tournament_entrant_members
FOR EACH ROW EXECUTE FUNCTION public.sync_phase2_identity_compatibility();

-- Shared club credentials are authorized in server application services. No
-- browser role gets direct table access; RLS remains the database backstop.
ALTER TABLE public.athletes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.club_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.club_member_athlete_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_sessions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.athletes FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.club_memberships FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.club_member_athlete_map FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.membership_assessments FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.group_sessions FROM PUBLIC, anon, authenticated;

COMMENT ON COLUMN public.groups.access_version IS
  'Increment to revoke every previously issued group session';
COMMENT ON TABLE public.athletes IS
  'Global sport identity; unclaimed athletes do not require an account';
COMMENT ON TABLE public.club_memberships IS
  'Effective-dated relationship between an athlete and a club; effective_to is exclusive';
COMMENT ON TABLE public.club_member_athlete_map IS
  'Lossless compatibility map from legacy club_members to Phase 2 identity';
COMMENT ON TABLE public.group_sessions IS
  'Server-only revocable sessions; session_key_hash never stores the signed cookie token';

COMMIT;
