-- PickHub Phase 2: durable manual duplicate-candidate review.
-- A review is audit evidence only. It never rewrites identity provenance or
-- merges athlete rows automatically.

BEGIN;

CREATE TABLE IF NOT EXISTS public.athlete_link_reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE RESTRICT,
  athlete_id bigint NOT NULL REFERENCES public.athletes(id) ON DELETE RESTRICT,
  candidate_athlete_id bigint NOT NULL REFERENCES public.athletes(id) ON DELETE RESTRICT,
  decision text NOT NULL CHECK (decision IN ('approve', 'reject')),
  reason text NOT NULL CHECK (btrim(reason) <> ''),
  actor_type text NOT NULL DEFAULT 'club_admin_session'
    CHECK (actor_type IN ('club_admin_session', 'platform_admin')),
  correlation_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (athlete_id <> candidate_athlete_id)
);

CREATE INDEX IF NOT EXISTS idx_athlete_link_reviews_group_created
  ON public.athlete_link_reviews(group_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_athlete_link_reviews_pair
  ON public.athlete_link_reviews(athlete_id, candidate_athlete_id, created_at DESC);

ALTER TABLE public.athlete_link_reviews ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.athlete_link_reviews FROM PUBLIC, anon, authenticated;

COMMENT ON TABLE public.athlete_link_reviews IS
  'Manual approve/reject audit for potential athlete links; does not merge or remap identities';

COMMIT;
