-- PickHub Phase 3: interclub tournament foundation.
-- Additive migration. Apply manually after migration 029; never auto-apply in production.

BEGIN;

ALTER TABLE public.tournaments
  ADD COLUMN IF NOT EXISTS organizer_type text NOT NULL DEFAULT 'platform',
  ADD COLUMN IF NOT EXISTS organizer_club_id bigint REFERENCES public.groups(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS organizer_community_id bigint,
  ADD COLUMN IF NOT EXISTS created_by_profile_id bigint,
  ADD COLUMN IF NOT EXISTS version bigint NOT NULL DEFAULT 1;

ALTER TABLE public.tournaments DROP CONSTRAINT IF EXISTS tournaments_organizer_scope_ck;
ALTER TABLE public.tournaments ADD CONSTRAINT tournaments_organizer_scope_ck CHECK (
  (organizer_type = 'platform' AND organizer_club_id IS NULL AND organizer_community_id IS NULL)
  OR (organizer_type = 'community' AND organizer_club_id IS NULL AND organizer_community_id IS NOT NULL)
  OR (organizer_type = 'club' AND organizer_club_id IS NOT NULL AND organizer_community_id IS NULL)
);
ALTER TABLE public.tournaments DROP CONSTRAINT IF EXISTS tournaments_organizer_type_ck;
ALTER TABLE public.tournaments ADD CONSTRAINT tournaments_organizer_type_ck
  CHECK (organizer_type IN ('platform', 'community', 'club'));
ALTER TABLE public.tournaments DROP CONSTRAINT IF EXISTS tournaments_version_positive;
ALTER TABLE public.tournaments ADD CONSTRAINT tournaments_version_positive CHECK (version > 0);

CREATE TABLE IF NOT EXISTS public.tournament_divisions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  tournament_id bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
  name text NOT NULL CHECK (btrim(name) <> ''),
  entrant_type text NOT NULL DEFAULT 'team' CHECK (entrant_type IN ('individual', 'pair', 'team')),
  capacity integer CHECK (capacity IS NULL OR capacity > 0),
  registration_opens_at timestamptz,
  registration_closes_at timestamptz,
  eligibility jsonb NOT NULL DEFAULT '{}'::jsonb,
  competition_template text NOT NULL DEFAULT 'interclub_friendly_team_v1',
  ruleset_version text NOT NULL DEFAULT '1',
  registration_status text NOT NULL DEFAULT 'closed' CHECK (registration_status IN ('closed', 'open', 'locked')),
  scheduling_status text NOT NULL DEFAULT 'pending' CHECK (scheduling_status IN ('pending', 'preview', 'committed', 'locked')),
  competition_status text NOT NULL DEFAULT 'pending' CHECK (competition_status IN ('pending', 'active', 'completed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (registration_closes_at IS NULL OR registration_opens_at IS NULL OR registration_closes_at > registration_opens_at)
);

CREATE TABLE IF NOT EXISTS public.tournament_clubs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  tournament_id bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
  club_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE RESTRICT,
  invitation_status text NOT NULL DEFAULT 'invited'
    CHECK (invitation_status IN ('invited', 'accepted', 'declined', 'roster_submitted', 'changes_requested', 'approved', 'withdrawn')),
  quota integer CHECK (quota IS NULL OR quota > 0),
  captain_contact_profile_id bigint,
  invitation_note text,
  version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tournament_id, club_id)
);

CREATE TABLE IF NOT EXISTS public.tournament_registrations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  division_id bigint NOT NULL REFERENCES public.tournament_divisions(id) ON DELETE CASCADE,
  tournament_club_id bigint NOT NULL REFERENCES public.tournament_clubs(id) ON DELETE CASCADE,
  athlete_id bigint REFERENCES public.athletes(id) ON DELETE RESTRICT,
  submitted_by_profile_id bigint,
  entrant_type text NOT NULL DEFAULT 'individual' CHECK (entrant_type IN ('individual', 'pair', 'team')),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'approved', 'changes_requested', 'rejected', 'withdrawn')),
  eligibility_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  captain_declaration jsonb NOT NULL DEFAULT '{}'::jsonb,
  private_note text,
  version bigint NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.tournament_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  division_id bigint NOT NULL REFERENCES public.tournament_divisions(id) ON DELETE CASCADE,
  tournament_club_id bigint NOT NULL REFERENCES public.tournament_clubs(id) ON DELETE RESTRICT,
  source_registration_id bigint REFERENCES public.tournament_registrations(id) ON DELETE SET NULL,
  name_snapshot text NOT NULL,
  color_snapshot text,
  seed integer,
  status text NOT NULL DEFAULT 'approved' CHECK (status IN ('draft', 'approved', 'withdrawn')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.tournament_entry_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  entry_id bigint NOT NULL REFERENCES public.tournament_entries(id) ON DELETE CASCADE,
  athlete_id bigint REFERENCES public.athletes(id) ON DELETE RESTRICT,
  display_name_snapshot text NOT NULL,
  club_name_snapshot text,
  skill_snapshot numeric(4, 2),
  roster_role text NOT NULL DEFAULT 'player' CHECK (roster_role IN ('player', 'captain', 'alternate')),
  UNIQUE (entry_id, athlete_id)
);

CREATE TABLE IF NOT EXISTS public.tournament_staff (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  tournament_id bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
  division_id bigint REFERENCES public.tournament_divisions(id) ON DELETE CASCADE,
  profile_id bigint NOT NULL,
  role text NOT NULL CHECK (role IN ('tournament_director', 'scorekeeper')),
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tournament_id, division_id, profile_id, role)
);

CREATE INDEX IF NOT EXISTS idx_tournament_divisions_group_tournament ON public.tournament_divisions(group_id, tournament_id);
CREATE INDEX IF NOT EXISTS idx_tournament_clubs_group_tournament ON public.tournament_clubs(group_id, tournament_id);
CREATE INDEX IF NOT EXISTS idx_tournament_registrations_group_division ON public.tournament_registrations(group_id, division_id);
CREATE INDEX IF NOT EXISTS idx_tournament_entries_group_division ON public.tournament_entries(group_id, division_id);
CREATE INDEX IF NOT EXISTS idx_tournament_entry_members_group_entry ON public.tournament_entry_members(group_id, entry_id);
CREATE INDEX IF NOT EXISTS idx_tournament_staff_group_tournament ON public.tournament_staff(group_id, tournament_id);

-- Giữ RLS bật theo trạng thái bảo vệ của module tournament hiện hữu.
-- Server dùng service-role + group_id/tournament scope để truy cập có kiểm soát.
ALTER TABLE public.tournament_divisions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournament_clubs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournament_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournament_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournament_entry_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournament_staff ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.tournament_clubs IS 'CLB được mời/tham gia giải liên CLB; captain chỉ được thao tác scope của CLB mình';
COMMENT ON TABLE public.tournament_registrations IS 'Đăng ký VĐV/đội với snapshot eligibility và ghi chú riêng';
COMMENT ON COLUMN public.tournaments.organizer_type IS 'platform, community hoặc club; Phase 3 triển khai platform và club';
COMMENT ON COLUMN public.tournament_divisions.competition_template IS 'Template luật, pilot dùng interclub_friendly_team_v1';

COMMIT;
