-- PickHub Phase 3 Task 2: platform identity and organizer authorization.
-- Forward-only and additive. Migration 030/031 are not modified.

BEGIN;

DO $$
DECLARE
  community_count bigint;
BEGIN
  SELECT count(*) INTO community_count
  FROM public.tournaments
  WHERE organizer_type = 'community';
  IF community_count <> 0 THEN
    RAISE EXCEPTION 'Phase 3 Task 2 blocked: expected 0 community tournaments before organizer constraint change, found %', community_count;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.platform_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login text NOT NULL,
  password_hash text NOT NULL,
  role text NOT NULL CHECK (role IN ('community_admin', 'platform_admin')),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  access_version bigint NOT NULL DEFAULT 1 CHECK (access_version > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.platform_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES public.platform_accounts(id) ON DELETE CASCADE,
  session_key_hash text NOT NULL UNIQUE,
  issued_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (expires_at > issued_at)
);

ALTER TABLE public.tournaments
  ADD COLUMN IF NOT EXISTS created_by_platform_account_id bigint
    REFERENCES public.platform_accounts(id) ON DELETE SET NULL;

ALTER TABLE public.tournaments DROP CONSTRAINT IF EXISTS tournaments_organizer_scope_ck;
ALTER TABLE public.tournaments ADD CONSTRAINT tournaments_organizer_scope_ck CHECK (
  (organizer_type = 'platform' AND organizer_club_id IS NULL AND organizer_community_id IS NULL)
  OR (organizer_type = 'community' AND organizer_club_id IS NULL)
  OR (organizer_type = 'club' AND organizer_club_id IS NOT NULL AND organizer_community_id IS NULL)
);

CREATE INDEX IF NOT EXISTS idx_platform_sessions_account_active
  ON public.platform_sessions(account_id, expires_at)
  WHERE revoked_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_platform_accounts_login_lower
  ON public.platform_accounts(lower(login));
CREATE INDEX IF NOT EXISTS idx_tournaments_platform_creator
  ON public.tournaments(created_by_platform_account_id);

ALTER TABLE public.platform_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_sessions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.platform_accounts, public.platform_sessions FROM PUBLIC, anon, authenticated;

COMMENT ON TABLE public.platform_accounts IS 'System-level actors; no public signup.';
COMMENT ON TABLE public.platform_sessions IS 'Separate platform_session backing records; group_session cannot authorize platform actions.';
COMMENT ON COLUMN public.tournaments.created_by_platform_account_id IS 'Platform actor for global community/platform tournaments; nullable during identity rollout.';

COMMIT;
