-- PickHub Phase 3 Task 4: division rules, external clubs, athletes and pairs.
-- Forward-only. 030/033/034 remain immutable.
-- Vocabulary decision: play_type is the user-facing source of truth for format;
-- legacy entrant_type is retained for compatibility but constrained to the
-- corresponding shape: singles->individual, doubles->pair, team->team.
BEGIN;

DO $$
DECLARE invalid_count bigint;
BEGIN
  SELECT count(*) INTO invalid_count FROM public.tournament_clubs
  WHERE club_id IS NULL;
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'Task 4 preflight: existing tournament_clubs without club_id=%', invalid_count;
  END IF;
END $$;

ALTER TABLE public.tournament_divisions
  ADD COLUMN IF NOT EXISTS play_type text NOT NULL DEFAULT 'team',
  ADD COLUMN IF NOT EXISTS scoring_scope text NOT NULL DEFAULT 'club',
  ADD COLUMN IF NOT EXISTS rating_policy text NOT NULL DEFAULT 'open',
  ADD COLUMN IF NOT EXISTS rating_cap numeric(4,2),
  ADD COLUMN IF NOT EXISTS pairing_mode text NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS scoring_override jsonb,
  ADD COLUMN IF NOT EXISTS tiebreak_override jsonb;
ALTER TABLE public.tournament_divisions
  DROP CONSTRAINT IF EXISTS tournament_divisions_play_type_ck,
  ADD CONSTRAINT tournament_divisions_play_type_ck CHECK (play_type IN ('singles', 'doubles', 'team')),
  DROP CONSTRAINT IF EXISTS tournament_divisions_scoring_scope_ck,
  ADD CONSTRAINT tournament_divisions_scoring_scope_ck CHECK (scoring_scope IN ('athlete', 'club')),
  DROP CONSTRAINT IF EXISTS tournament_divisions_rating_policy_ck,
  ADD CONSTRAINT tournament_divisions_rating_policy_ck CHECK (rating_policy IN ('open', 'capped')),
  DROP CONSTRAINT IF EXISTS tournament_divisions_rating_cap_ck,
  ADD CONSTRAINT tournament_divisions_rating_cap_ck CHECK (rating_policy <> 'capped' OR (rating_cap IS NOT NULL AND rating_cap > 0)),
  DROP CONSTRAINT IF EXISTS tournament_divisions_pairing_mode_ck,
  ADD CONSTRAINT tournament_divisions_pairing_mode_ck CHECK (pairing_mode IN ('none', 'manual', 'random_balanced')),
  DROP CONSTRAINT IF EXISTS tournament_divisions_entrant_type_relation_ck,
  ADD CONSTRAINT tournament_divisions_entrant_type_relation_ck CHECK (
    (play_type = 'singles' AND entrant_type = 'individual')
    OR (play_type = 'doubles' AND entrant_type = 'pair')
    OR (play_type = 'team' AND entrant_type = 'team')
  );

ALTER TABLE public.tournaments
  ADD COLUMN IF NOT EXISTS default_scoring jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS tiebreak_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS share_settings jsonb NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS public.tournament_external_clubs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  name text NOT NULL CHECK (btrim(name) <> ''),
  contact_name text,
  contact_channel text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (group_id, name)
);

ALTER TABLE public.tournament_clubs
  ALTER COLUMN club_id DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS external_club_id bigint REFERENCES public.tournament_external_clubs(id) ON DELETE RESTRICT;
ALTER TABLE public.tournament_clubs
  DROP CONSTRAINT IF EXISTS tournament_clubs_tournament_id_club_id_key,
  DROP CONSTRAINT IF EXISTS tournament_clubs_exactly_one_reference_ck,
  ADD CONSTRAINT tournament_clubs_exactly_one_reference_ck CHECK ((club_id IS NULL) <> (external_club_id IS NULL));
CREATE UNIQUE INDEX IF NOT EXISTS idx_tournament_clubs_tournament_club
  ON public.tournament_clubs(tournament_id, club_id) WHERE club_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_tournament_clubs_tournament_external
  ON public.tournament_clubs(tournament_id, external_club_id) WHERE external_club_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.tournament_athletes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  tournament_id bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
  tournament_club_id bigint NOT NULL REFERENCES public.tournament_clubs(id) ON DELETE CASCADE,
  athlete_id bigint REFERENCES public.athletes(id) ON DELETE RESTRICT,
  display_name_snapshot text,
  club_name_snapshot text,
  phr_rating numeric(4,2),
  phr_status text NOT NULL DEFAULT 'unverified' CHECK (phr_status IN ('unverified', 'pending', 'confirmed')),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (athlete_id IS NOT NULL OR btrim(COALESCE(display_name_snapshot, '')) <> ''),
  CHECK (phr_rating IS NULL OR phr_rating >= 0),
  UNIQUE (tournament_id, athlete_id)
);

CREATE TABLE IF NOT EXISTS public.tournament_athlete_phr_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  tournament_athlete_id bigint NOT NULL REFERENCES public.tournament_athletes(id) ON DELETE CASCADE,
  phr_rating numeric(4,2) NOT NULL CHECK (phr_rating >= 0),
  status text NOT NULL CHECK (status IN ('unverified', 'pending', 'confirmed')),
  recorded_by_profile_id bigint,
  recorded_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.tournament_registrations
  ADD COLUMN IF NOT EXISTS submitted_by_actor text NOT NULL DEFAULT 'club_admin',
  ADD COLUMN IF NOT EXISTS club_confirmation_status text NOT NULL DEFAULT 'pending'
    CHECK (club_confirmation_status IN ('pending', 'confirmed', 'rejected')),
  ADD COLUMN IF NOT EXISTS confirmed_at timestamptz;

CREATE TABLE IF NOT EXISTS public.tournament_pairs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  division_id bigint NOT NULL REFERENCES public.tournament_divisions(id) ON DELETE CASCADE,
  name_snapshot text,
  pairing_mode text NOT NULL CHECK (pairing_mode IN ('manual', 'random_balanced')),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'confirmed', 'locked')),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.tournament_pair_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  pair_id bigint NOT NULL REFERENCES public.tournament_pairs(id) ON DELETE CASCADE,
  tournament_athlete_id bigint NOT NULL REFERENCES public.tournament_athletes(id) ON DELETE RESTRICT,
  role text NOT NULL DEFAULT 'player' CHECK (role IN ('player', 'captain')),
  UNIQUE (pair_id, tournament_athlete_id)
);

CREATE INDEX IF NOT EXISTS idx_tournament_athletes_tournament_club
  ON public.tournament_athletes(tournament_id, tournament_club_id);
CREATE INDEX IF NOT EXISTS idx_tournament_pairs_division
  ON public.tournament_pairs(division_id);
ALTER TABLE public.tournament_external_clubs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournament_athletes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournament_athlete_phr_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournament_pairs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tournament_pair_members ENABLE ROW LEVEL SECURITY;

COMMIT;
