-- Phase 4 vận hành giải: check-in, địa điểm, lịch sân, score audit và correction.
-- Additive/idempotent; mọi bảng đều giữ tenant + division scope.
BEGIN;
ALTER TABLE public.tournament_divisions ADD COLUMN IF NOT EXISTS schedule_publication_status text NOT NULL DEFAULT 'draft';
ALTER TABLE public.tournament_divisions ADD COLUMN IF NOT EXISTS schedule_publication_version integer NOT NULL DEFAULT 1;
CREATE TABLE IF NOT EXISTS public.tournament_venues (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
 tournament_id bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE, name text NOT NULL, address text, timezone text, contact text, map_link text, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.tournament_courts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
 tournament_id bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE, venue_id bigint NOT NULL REFERENCES public.tournament_venues(id) ON DELETE CASCADE, label text NOT NULL, surface text, active boolean NOT NULL DEFAULT true, availability jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE TABLE IF NOT EXISTS public.tournament_time_slots (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
 tournament_id bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE, division_id bigint NOT NULL REFERENCES public.tournament_divisions(id) ON DELETE CASCADE, start_at timestamptz NOT NULL, end_at timestamptz NOT NULL, court_capacity integer NOT NULL DEFAULT 1, status text NOT NULL DEFAULT 'open'
);
CREATE TABLE IF NOT EXISTS public.tournament_check_ins (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
 tournament_id bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE, division_id bigint NOT NULL REFERENCES public.tournament_divisions(id) ON DELETE CASCADE, entry_id bigint REFERENCES public.tournament_entries(id) ON DELETE CASCADE, athlete_id bigint REFERENCES public.tournament_athletes(id) ON DELETE CASCADE, status text NOT NULL DEFAULT 'checked_in', method text NOT NULL DEFAULT 'manual', actor text, checked_in_at timestamptz NOT NULL DEFAULT now(), client_mutation_id text
);
CREATE TABLE IF NOT EXISTS public.tournament_match_assignments (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
 tournament_id bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE, division_id bigint NOT NULL REFERENCES public.tournament_divisions(id) ON DELETE CASCADE, match_id bigint NOT NULL REFERENCES public.tournament_matches(id) ON DELETE CASCADE, court_id bigint REFERENCES public.tournament_courts(id) ON DELETE SET NULL, time_slot_id bigint REFERENCES public.tournament_time_slots(id) ON DELETE SET NULL, scheduled_start timestamptz, scheduled_end timestamptz, version integer NOT NULL DEFAULT 1, status text NOT NULL DEFAULT 'assigned', locked boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.tournament_match_assignments ADD COLUMN IF NOT EXISTS tournament_id bigint REFERENCES public.tournaments(id) ON DELETE CASCADE;
CREATE TABLE IF NOT EXISTS public.tournament_score_submissions (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE, division_id bigint NOT NULL REFERENCES public.tournament_divisions(id) ON DELETE CASCADE, match_id bigint NOT NULL REFERENCES public.tournament_matches(id) ON DELETE CASCADE, payload jsonb NOT NULL, client_mutation_id text NOT NULL, actor text, device_timestamp timestamptz, server_timestamp timestamptz NOT NULL DEFAULT now(), version integer NOT NULL DEFAULT 1, UNIQUE(group_id, match_id, client_mutation_id)
);
CREATE TABLE IF NOT EXISTS public.tournament_result_corrections (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE, tournament_id bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE, division_id bigint NOT NULL REFERENCES public.tournament_divisions(id) ON DELETE CASCADE, match_id bigint NOT NULL REFERENCES public.tournament_matches(id) ON DELETE CASCADE, before_payload jsonb NOT NULL, after_payload jsonb NOT NULL, reason text NOT NULL, requester text, approver text, status text NOT NULL DEFAULT 'requested', requested_at timestamptz NOT NULL DEFAULT now(), approved_at timestamptz, applied_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_phase4_venue_tenant ON public.tournament_venues(group_id, tournament_id);
CREATE INDEX IF NOT EXISTS idx_phase4_court_tenant ON public.tournament_courts(group_id, tournament_id, venue_id);
CREATE INDEX IF NOT EXISTS idx_phase4_slot_scope ON public.tournament_time_slots(group_id, tournament_id, division_id, start_at);
CREATE INDEX IF NOT EXISTS idx_phase4_checkin_scope ON public.tournament_check_ins(group_id, tournament_id, division_id, entry_id, athlete_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_phase4_checkin_identity ON public.tournament_check_ins(group_id, division_id, coalesce(entry_id, 0), coalesce(athlete_id, 0));
CREATE INDEX IF NOT EXISTS idx_phase4_assignment_scope ON public.tournament_match_assignments(group_id, tournament_id, division_id, match_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_phase4_assignment_identity ON public.tournament_match_assignments(group_id, match_id);
CREATE INDEX IF NOT EXISTS idx_phase4_submission_scope ON public.tournament_score_submissions(group_id, division_id, match_id);
CREATE INDEX IF NOT EXISTS idx_phase4_correction_scope ON public.tournament_result_corrections(group_id, division_id, match_id, status);
COMMENT ON TABLE public.tournament_result_corrections IS 'Audit bắt buộc khi sửa kết quả đã finalized.';
COMMIT;
