-- Phase 4: score submission, QR check-in replay protection và correction atomic.
-- Additive/idempotent; chỉ service_role được gọi RPC qua server route.
BEGIN;

CREATE TABLE IF NOT EXISTS public.tournament_qr_checkin_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  tournament_id bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
  division_id bigint NOT NULL REFERENCES public.tournament_divisions(id) ON DELETE CASCADE,
  entry_id bigint REFERENCES public.tournament_entries(id) ON DELETE CASCADE,
  athlete_id bigint REFERENCES public.tournament_athletes(id) ON DELETE CASCADE,
  token_hash text NOT NULL,
  client_mutation_id text,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(group_id, token_hash)
);
CREATE INDEX IF NOT EXISTS idx_phase4_qr_checkin_scope ON public.tournament_qr_checkin_tokens(group_id, tournament_id, division_id, expires_at);
CREATE INDEX IF NOT EXISTS idx_phase4_qr_checkin_replay ON public.tournament_qr_checkin_tokens(group_id, client_mutation_id);

CREATE OR REPLACE FUNCTION public.submit_tournament_score(
  p_group_id bigint, p_tournament_id bigint, p_division_id bigint, p_match_id bigint,
  p_games jsonb, p_winner_entrant_id bigint DEFAULT NULL, p_status text DEFAULT 'submitted',
  p_parent_field text DEFAULT NULL, p_expected_version integer DEFAULT NULL,
  p_client_mutation_id text DEFAULT NULL, p_actor text DEFAULT 'admin',
  p_device_timestamp timestamptz DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE result jsonb; replay jsonb; match_row public.tournament_matches%ROWTYPE;
BEGIN
  IF p_client_mutation_id IS NULL OR length(trim(p_client_mutation_id)) = 0 THEN RAISE EXCEPTION 'client_mutation_id is required' USING ERRCODE='22023'; END IF;
  SELECT response INTO replay FROM public.pickhub_mutation_idempotency
    WHERE group_id=p_group_id AND operation='submit_tournament_score' AND idempotency_key=p_client_mutation_id FOR UPDATE;
  IF replay IS NOT NULL THEN RETURN replay; END IF;
  SELECT * INTO match_row FROM public.tournament_matches WHERE id=p_match_id AND group_id=p_group_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'match not found' USING ERRCODE='P0002'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.tournament_divisions WHERE id=p_division_id AND tournament_id=p_tournament_id AND group_id=p_group_id) THEN RAISE EXCEPTION 'division does not belong to tournament' USING ERRCODE='23503'; END IF;
  IF p_expected_version IS NOT NULL AND match_row.version <> p_expected_version THEN RAISE EXCEPTION 'match version conflict' USING ERRCODE='40001'; END IF;
  result := public.replace_tournament_games(p_group_id,p_match_id,p_games,p_winner_entrant_id,p_status,p_parent_field,p_expected_version,p_client_mutation_id);
  INSERT INTO public.tournament_score_submissions(group_id,division_id,match_id,payload,client_mutation_id,actor,device_timestamp,version)
    VALUES (p_group_id,p_division_id,p_match_id,jsonb_build_object('games',p_games,'winner_entrant_id',p_winner_entrant_id,'status',p_status),p_client_mutation_id,p_actor,p_device_timestamp,((result->>'version')::integer));
  INSERT INTO public.pickhub_mutation_idempotency(group_id,operation,idempotency_key,response,response_hash)
    VALUES(p_group_id,'submit_tournament_score',p_client_mutation_id,result,md5(result::text));
  RETURN result;
END; $$;

CREATE OR REPLACE FUNCTION public.consume_tournament_qr_checkin(
  p_group_id bigint, p_tournament_id bigint, p_division_id bigint, p_token_hash text,
  p_entry_id bigint DEFAULT NULL, p_athlete_id bigint DEFAULT NULL, p_client_mutation_id text DEFAULT NULL,
  p_actor text DEFAULT 'admin'
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE token_row public.tournament_qr_checkin_tokens%ROWTYPE; checkin_row public.tournament_check_ins%ROWTYPE;
BEGIN
  SELECT * INTO token_row FROM public.tournament_qr_checkin_tokens WHERE group_id=p_group_id AND token_hash=p_token_hash FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'QR token không hợp lệ' USING ERRCODE='P0002'; END IF;
  IF token_row.tournament_id<>p_tournament_id OR token_row.division_id<>p_division_id THEN RAISE EXCEPTION 'QR token không đúng giải/nội dung' USING ERRCODE='22023'; END IF;
  IF token_row.used_at IS NOT NULL THEN RAISE EXCEPTION 'QR token đã được sử dụng' USING ERRCODE='40001'; END IF;
  IF token_row.expires_at <= now() THEN RAISE EXCEPTION 'QR token đã hết hạn' USING ERRCODE='22023'; END IF;
  IF p_entry_id IS NULL AND p_athlete_id IS NULL THEN RAISE EXCEPTION 'entry_id hoặc athlete_id là bắt buộc' USING ERRCODE='22023'; END IF;
  UPDATE public.tournament_qr_checkin_tokens SET used_at=now() WHERE id=token_row.id;
  SELECT * INTO checkin_row FROM public.tournament_check_ins
    WHERE group_id=p_group_id AND division_id=p_division_id
      AND COALESCE(entry_id,0)=COALESCE(COALESCE(p_entry_id,token_row.entry_id),0)
      AND COALESCE(athlete_id,0)=COALESCE(COALESCE(p_athlete_id,token_row.athlete_id),0) FOR UPDATE;
  IF FOUND THEN
    UPDATE public.tournament_check_ins SET status='checked_in',method='qr',actor=p_actor,checked_in_at=now(),client_mutation_id=p_client_mutation_id WHERE id=checkin_row.id RETURNING * INTO checkin_row;
  ELSE
    INSERT INTO public.tournament_check_ins(group_id,tournament_id,division_id,entry_id,athlete_id,status,method,actor,client_mutation_id)
      VALUES(p_group_id,p_tournament_id,p_division_id,COALESCE(p_entry_id,token_row.entry_id),COALESCE(p_athlete_id,token_row.athlete_id),'checked_in','qr',p_actor,p_client_mutation_id)
      RETURNING * INTO checkin_row;
  END IF;
  RETURN jsonb_build_object('success',true,'check_in',to_jsonb(checkin_row),'token_id',token_row.id);
END; $$;

CREATE OR REPLACE FUNCTION public.apply_tournament_result_correction(
  p_group_id bigint, p_correction_id bigint, p_division_id bigint, p_expected_version integer DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE c public.tournament_result_corrections%ROWTYPE; m public.tournament_matches%ROWTYPE; payload jsonb; result jsonb;
BEGIN
  SELECT * INTO c FROM public.tournament_result_corrections WHERE id=p_correction_id AND group_id=p_group_id AND division_id=p_division_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'correction not found' USING ERRCODE='P0002'; END IF;
  IF c.status='applied' THEN RETURN jsonb_build_object('success',true,'correction_id',c.id,'status','applied'); END IF;
  IF c.status <> 'approved' THEN RAISE EXCEPTION 'correction must be approved before apply' USING ERRCODE='22023'; END IF;
  SELECT * INTO m FROM public.tournament_matches WHERE id=c.match_id AND group_id=p_group_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'match not found' USING ERRCODE='P0002'; END IF;
  IF p_expected_version IS NOT NULL AND m.version<>p_expected_version THEN RAISE EXCEPTION 'match version conflict' USING ERRCODE='40001'; END IF;
  payload := CASE WHEN jsonb_typeof(c.after_payload->'games')='array' THEN c.after_payload->'games' ELSE c.after_payload END;
  result := public.replace_tournament_games(p_group_id,m.id,payload,NULL,'done',NULL,p_expected_version,format('correction:%s',c.id));
  UPDATE public.tournament_result_corrections SET status='applied',applied_at=now() WHERE id=c.id AND group_id=p_group_id AND division_id=p_division_id;
  RETURN result || jsonb_build_object('success',true,'correction_id',c.id,'status','applied');
END; $$;

REVOKE ALL ON FUNCTION public.submit_tournament_score(bigint,bigint,bigint,bigint,jsonb,bigint,text,text,integer,text,text,timestamptz) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.consume_tournament_qr_checkin(bigint,bigint,bigint,text,bigint,bigint,text,text) FROM PUBLIC,anon,authenticated;
REVOKE ALL ON FUNCTION public.apply_tournament_result_correction(bigint,bigint,bigint,integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.submit_tournament_score(bigint,bigint,bigint,bigint,jsonb,bigint,text,text,integer,text,text,timestamptz) TO service_role;
GRANT EXECUTE ON FUNCTION public.consume_tournament_qr_checkin(bigint,bigint,bigint,text,bigint,bigint,text,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_tournament_result_correction(bigint,bigint,bigint,integer) TO service_role;
COMMENT ON TABLE public.tournament_qr_checkin_tokens IS 'QR check-in token dùng một lần, chống replay trong vận hành giải.';
COMMIT;
