-- Phase 4: thông báo và sổ thu chi giải đấu. Additive/idempotent.
BEGIN;
CREATE TABLE IF NOT EXISTS public.tournament_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  tournament_id bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
  division_id bigint REFERENCES public.tournament_divisions(id) ON DELETE CASCADE,
  recipient text NOT NULL, channel text NOT NULL DEFAULT 'in_app', template text NOT NULL DEFAULT 'generic',
  payload jsonb NOT NULL DEFAULT '{}'::jsonb, status text NOT NULL DEFAULT 'queued', provider text,
  provider_error text, sent_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.tournament_finance_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  tournament_id bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
  division_id bigint REFERENCES public.tournament_divisions(id) ON DELETE CASCADE,
  entry_id bigint REFERENCES public.tournament_entries(id) ON DELETE SET NULL,
  entrant_id bigint REFERENCES public.tournament_entrants(id) ON DELETE SET NULL,
  amount numeric(14,2) NOT NULL CHECK (amount <> 0), currency text NOT NULL DEFAULT 'VND',
  kind text NOT NULL DEFAULT 'adjustment', description text, external_ref text,
  status text NOT NULL DEFAULT 'posted', reversal_of_id bigint REFERENCES public.tournament_finance_ledger(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_tournament_notifications_scope ON public.tournament_notifications(group_id, tournament_id, status);
CREATE INDEX IF NOT EXISTS idx_tournament_finance_scope ON public.tournament_finance_ledger(group_id, tournament_id, division_id, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tournament_finance_reversal ON public.tournament_finance_ledger(group_id, reversal_of_id) WHERE reversal_of_id IS NOT NULL;
COMMENT ON TABLE public.tournament_finance_ledger IS 'Sổ thu chi giải đấu; hoàn tác ghi một dòng đảo chiều, không sửa dòng gốc.';
COMMIT;
