-- 043: Thông báo cấp CLB và công tắc huy hiệu BXH. Additive, idempotent.
BEGIN;

CREATE TABLE IF NOT EXISTS public.club_notifications (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id     bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  kind         text   NOT NULL,
  subject_type text,
  subject_id   bigint,
  payload      jsonb  NOT NULL DEFAULT '{}'::jsonb,
  status       text   NOT NULL DEFAULT 'open',
  resolved_at  timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT club_notifications_status_check CHECK (status IN ('open', 'resolved', 'dismissed'))
);

CREATE INDEX IF NOT EXISTS idx_club_notifications_open
  ON public.club_notifications(group_id, status, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_club_notifications_subject
  ON public.club_notifications(group_id, kind, subject_type, subject_id)
  WHERE subject_id IS NOT NULL;

ALTER TABLE public.groups
  ADD COLUMN IF NOT EXISTS shame_badges_enabled boolean NOT NULL DEFAULT true;

COMMENT ON TABLE public.club_notifications IS
  'Hàng đợi việc cần trưởng nhóm xử lý ở cấp CLB. Không dùng làm dòng thời gian tin tức.';

COMMIT;