-- 045_tournament_operation_logs.sql
-- Nhật ký thao tác điều hành giải. Dùng chung cho vòng đời giải (Spec 0),
-- bàn điều hành (Spec 2) và sửa kết quả (Spec 3).
-- Idempotent; chỉ thêm bảng mới, không phá huỷ dữ liệu.

CREATE TABLE IF NOT EXISTS public.tournament_operation_logs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id      bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  tournament_id bigint NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
  division_id   bigint REFERENCES public.tournament_divisions(id) ON DELETE SET NULL,
  actor         text NOT NULL,
  action        text NOT NULL,
  target_type   text NOT NULL,
  target_id     bigint,
  before        jsonb,
  after         jsonb,
  reason        text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tournament_operation_logs_tournament
  ON public.tournament_operation_logs(group_id, tournament_id, created_at DESC);

ALTER TABLE public.tournament_operation_logs DISABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.tournament_operation_logs IS 'Nhat ky thao tac dieu hanh giai; chi doc, khong sua khong xoa';
COMMENT ON COLUMN public.tournament_operation_logs.action IS 'tournament_status_changed, court_toggled, match_called, result_corrected, ...';
