-- 048_athlete_accounts.sql
-- Tài khoản cá nhân của VĐV, liên kết 1-1 với một athlete đã có trong CLB.
-- Additive & idempotent: không đụng platform_accounts (actor hệ thống) và không sửa athletes.

BEGIN;

CREATE TABLE IF NOT EXISTS public.athlete_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login text NOT NULL CHECK (btrim(login) <> ''),
  password_hash text NOT NULL,
  display_name text NOT NULL CHECK (btrim(display_name) <> ''),
  athlete_id bigint NOT NULL UNIQUE REFERENCES public.athletes(id) ON DELETE RESTRICT,
  club_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE RESTRICT,
  club_membership_id bigint NOT NULL REFERENCES public.club_memberships(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  access_version bigint NOT NULL DEFAULT 1 CHECK (access_version > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.athlete_account_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES public.athlete_accounts(id) ON DELETE CASCADE,
  session_key_hash text NOT NULL UNIQUE,
  issued_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (expires_at > issued_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_athlete_accounts_login_lower
  ON public.athlete_accounts(lower(login));
CREATE INDEX IF NOT EXISTS idx_athlete_accounts_club
  ON public.athlete_accounts(club_id, status);
CREATE INDEX IF NOT EXISTS idx_athlete_account_sessions_active
  ON public.athlete_account_sessions(account_id, expires_at)
  WHERE revoked_at IS NULL;

ALTER TABLE public.athlete_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.athlete_account_sessions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.athlete_accounts, public.athlete_account_sessions
  FROM PUBLIC, anon, authenticated;

COMMENT ON TABLE public.athlete_accounts IS
  'Tài khoản VĐV tự đăng ký và liên kết với athlete/membership có sẵn trong CLB; tách biệt platform_accounts.';
COMMENT ON COLUMN public.athlete_accounts.athlete_id IS
  'Một athlete chỉ được một tài khoản nhận; ràng buộc UNIQUE chống nhận trùng hồ sơ.';

COMMIT;
