-- Harden pair-entry integrity and introduce a revision-aware pair confirmation path.
-- This is forward-only: legacy rows are not inferred or rewritten.
BEGIN;

ALTER TABLE public.tournament_entries
  DROP CONSTRAINT IF EXISTS tournament_entries_pair_id_fk,
  ADD CONSTRAINT tournament_entries_pair_id_fk
    FOREIGN KEY (pair_id) REFERENCES public.tournament_pairs(id) ON DELETE RESTRICT
    NOT VALID;

CREATE TABLE IF NOT EXISTS public.tournament_setup_mutations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  operation text NOT NULL,
  division_id bigint NOT NULL REFERENCES public.tournament_divisions(id) ON DELETE CASCADE,
  idempotency_key text NOT NULL CHECK (length(btrim(idempotency_key)) BETWEEN 1 AND 200),
  payload_fingerprint text NOT NULL,
  response jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (group_id, operation, idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_tournament_setup_mutations_scope
  ON public.tournament_setup_mutations(group_id, operation, division_id, idempotency_key);
ALTER TABLE public.tournament_setup_mutations DISABLE ROW LEVEL SECURITY;

-- Migration 060 is already deployed. Its original readiness projection is
-- extended here rather than altering the historical migration file.
CREATE OR REPLACE FUNCTION public.get_tournament_division_readiness(
  p_group_id bigint,
  p_tournament_id bigint,
  p_division_id bigint
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  d public.tournament_divisions%ROWTYPE;
  entry_count integer := 0;
  pair_count integer := 0;
  roster_count integer := 0;
  paired_athlete_count integer := 0;
  reasons jsonb := '[]'::jsonb;
BEGIN
  SELECT * INTO d FROM public.tournament_divisions
  WHERE id = p_division_id AND group_id = p_group_id AND tournament_id = p_tournament_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'division not found in tournament scope' USING ERRCODE = 'P0002'; END IF;

  SELECT count(*)::integer INTO entry_count FROM public.tournament_entries e
  WHERE e.group_id = p_group_id AND e.division_id = p_division_id AND e.status = 'approved';
  SELECT count(*)::integer INTO roster_count FROM public.tournament_athletes a
  WHERE a.group_id = p_group_id AND a.tournament_id = p_tournament_id;

  IF entry_count < 2 THEN
    reasons := reasons || jsonb_build_array(jsonb_build_object('code', 'ENTRY_COUNT_TOO_LOW', 'entity_id', p_division_id, 'message', 'Cần ít nhất 2 entry đã duyệt để bốc thăm.'));
  END IF;

  IF d.play_type = 'doubles' THEN
    SELECT count(*)::integer INTO pair_count FROM public.tournament_pairs p
    WHERE p.group_id = p_group_id AND p.division_id = p_division_id AND p.status IN ('confirmed', 'locked');
    SELECT count(DISTINCT pm.tournament_athlete_id)::integer INTO paired_athlete_count
    FROM public.tournament_pair_members pm JOIN public.tournament_pairs p ON p.id = pm.pair_id
    WHERE pm.group_id = p_group_id AND p.group_id = p_group_id AND p.division_id = p_division_id AND p.status IN ('confirmed', 'locked');

    SELECT COALESCE(jsonb_agg(reason ORDER BY reason->>'code', (reason->>'entity_id')::bigint), '[]'::jsonb) INTO reasons
    FROM (
      SELECT jsonb_build_object('code', 'PAIR_MEMBER_COUNT_INVALID', 'entity_id', p.id, 'message', 'Mỗi cặp đã xác nhận phải có đúng 2 vận động viên.') AS reason
      FROM public.tournament_pairs p LEFT JOIN public.tournament_pair_members pm ON pm.pair_id = p.id AND pm.group_id = p_group_id
      WHERE p.group_id = p_group_id AND p.division_id = p_division_id AND p.status IN ('confirmed', 'locked')
      GROUP BY p.id HAVING count(pm.id) <> 2
      UNION ALL
      SELECT jsonb_build_object('code', 'ATHLETE_IN_MULTIPLE_PAIRS', 'entity_id', pm.tournament_athlete_id, 'message', 'Một vận động viên không được thuộc nhiều cặp trong cùng nội dung.')
      FROM public.tournament_pair_members pm JOIN public.tournament_pairs p ON p.id = pm.pair_id
      WHERE pm.group_id = p_group_id AND p.group_id = p_group_id AND p.division_id = p_division_id AND p.status IN ('confirmed', 'locked')
      GROUP BY pm.tournament_athlete_id HAVING count(DISTINCT pm.pair_id) > 1
      UNION ALL
      SELECT jsonb_build_object('code', 'PAIR_ENTRY_LINK_MISSING', 'entity_id', p.id, 'message', 'Cặp đã xác nhận chưa có entry liên kết trực tiếp.')
      FROM public.tournament_pairs p WHERE p.group_id = p_group_id AND p.division_id = p_division_id AND p.status IN ('confirmed', 'locked')
      AND NOT EXISTS (SELECT 1 FROM public.tournament_entries e WHERE e.group_id = p_group_id AND e.division_id = p_division_id AND e.pair_id = p.id AND e.status = 'approved')
      UNION ALL
      SELECT jsonb_build_object('code', 'APPROVED_DOUBLES_ENTRY_PAIR_ID_MISSING', 'entity_id', e.id, 'message', 'Entry đôi đã duyệt phải liên kết trực tiếp với một cặp.')
      FROM public.tournament_entries e WHERE e.group_id = p_group_id AND e.division_id = p_division_id AND e.status = 'approved' AND e.pair_id IS NULL
      UNION ALL
      SELECT jsonb_build_object('code', 'PAIR_ENTRY_COUNT_MISMATCH', 'entity_id', p_division_id, 'message', 'Số cặp đã xác nhận phải khớp chính xác số entry đôi đã duyệt.')
      WHERE pair_count <> entry_count
      UNION ALL
      SELECT jsonb_build_object('code', 'ENTRY_MEMBER_SNAPSHOT_MISMATCH', 'entity_id', e.id, 'message', 'Thành viên snapshot của entry không khớp cặp liên kết.')
      FROM public.tournament_entries e JOIN public.tournament_pairs p ON p.id = e.pair_id
      WHERE e.group_id = p_group_id AND e.division_id = p_division_id AND e.status = 'approved' AND p.group_id = p_group_id AND p.division_id = p_division_id
      AND ((SELECT count(*) FROM public.tournament_entry_members em WHERE em.group_id = p_group_id AND em.entry_id = e.id) <> 2
        OR EXISTS (SELECT 1 FROM public.tournament_pair_members pm JOIN public.tournament_athletes a ON a.id = pm.tournament_athlete_id WHERE pm.group_id = p_group_id AND pm.pair_id = p.id AND NOT EXISTS (SELECT 1 FROM public.tournament_entry_members em WHERE em.group_id = p_group_id AND em.entry_id = e.id AND em.athlete_id IS NOT DISTINCT FROM a.athlete_id AND em.display_name_snapshot IS NOT DISTINCT FROM a.display_name_snapshot)))
    ) computed_reasons;
    IF entry_count < 2 THEN reasons := reasons || jsonb_build_array(jsonb_build_object('code', 'ENTRY_COUNT_TOO_LOW', 'entity_id', p_division_id, 'message', 'Cần ít nhất 2 entry đã duyệt để bốc thăm.')); END IF;
  END IF;

  RETURN jsonb_build_object('division_id', d.id, 'tournament_id', d.tournament_id, 'revision', d.setup_revision,
    'roster_lock_status', d.roster_lock_status, 'roster_locked_at', d.roster_locked_at, 'roster_locked_by', d.roster_locked_by,
    'status', CASE WHEN jsonb_array_length(reasons) > 0 THEN 'blocked' ELSE 'ready' END, 'reasons', reasons,
    'counts', jsonb_build_object('roster', roster_count, 'pairs', pair_count, 'entries', entry_count, 'paired_athletes', paired_athlete_count, 'unpaired', GREATEST(roster_count - paired_athlete_count, 0)), 'legacy_compatible', true);
END;
$$;

REVOKE ALL ON FUNCTION public.get_tournament_division_readiness(bigint, bigint, bigint) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_division_readiness(bigint, bigint, bigint) TO service_role;

CREATE OR REPLACE FUNCTION public.confirm_tournament_pairs_revisioned(
  p_group_id bigint,
  p_division_id bigint,
  p_pairs jsonb,
  p_pairing_mode text,
  p_expected_setup_revision bigint,
  p_idempotency_key text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  d public.tournament_divisions%ROWTYPE;
  pair jsonb;
  mem jsonb;
  athlete public.tournament_athletes%ROWTYPE;
  pair_row public.tournament_pairs%ROWTYPE;
  entry_row public.tournament_entries%ROWTYPE;
  cached public.tournament_setup_mutations%ROWTYPE;
  legacy_response jsonb;
  ids bigint[];
  name text;
  first_club bigint;
  pair_count integer := 0;
  pair_ids jsonb := '[]'::jsonb;
  entry_ids jsonb := '[]'::jsonb;
  created_pairs jsonb := '[]'::jsonb;
  payload_fingerprint text;
  result jsonb;
BEGIN
  IF p_expected_setup_revision IS NULL OR p_expected_setup_revision < 1 THEN
    RAISE EXCEPTION 'SETUP_REVISION_CONFLICT' USING ERRCODE = '40001';
  END IF;
  IF p_idempotency_key IS NULL OR length(btrim(p_idempotency_key)) NOT BETWEEN 1 AND 200 THEN
    RAISE EXCEPTION 'SETUP_PAYLOAD_INVALID' USING ERRCODE = '22023';
  END IF;
  IF COALESCE(jsonb_typeof(p_pairs), '') <> 'array' OR jsonb_array_length(p_pairs) = 0
    OR p_pairing_mode NOT IN ('manual', 'random_balanced') THEN
    RAISE EXCEPTION 'SETUP_PAYLOAD_INVALID' USING ERRCODE = '22023';
  END IF;

  -- jsonb normalizes object-key order; confirmPairing has already canonicalized pair members.
  payload_fingerprint := md5(jsonb_build_object(
    'division_id', p_division_id, 'pairs', p_pairs, 'pairing_mode', p_pairing_mode
  )::text);
  PERFORM pg_advisory_xact_lock(hashtextextended(
    p_group_id::text || ':revisioned-pairs:' || p_idempotency_key, 0
  ));

  SELECT * INTO cached FROM public.tournament_setup_mutations
  WHERE group_id = p_group_id
    AND operation = 'confirm_tournament_pairs_revisioned'
    AND idempotency_key = p_idempotency_key
  FOR UPDATE;
  IF FOUND THEN
    IF cached.division_id <> p_division_id OR cached.payload_fingerprint <> payload_fingerprint THEN
      RAISE EXCEPTION 'IDEMPOTENCY_KEY_REUSED' USING ERRCODE = '22023';
    END IF;
    RETURN cached.response;
  END IF;

  -- Do not let a key from the unscoped legacy operation select a different replay semantic.
  SELECT response INTO legacy_response FROM public.pickhub_mutation_idempotency
  WHERE group_id = p_group_id
    AND operation = 'create_tournament_pairs_atomic'
    AND idempotency_key = p_idempotency_key;
  IF FOUND THEN
    RAISE EXCEPTION 'LEGACY_IDEMPOTENCY_RECORD_UNSAFE' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO d FROM public.tournament_divisions
  WHERE id = p_division_id AND group_id = p_group_id
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'division not found' USING ERRCODE = 'P0002'; END IF;
  IF d.setup_revision <> p_expected_setup_revision THEN
    RAISE EXCEPTION 'SETUP_REVISION_CONFLICT' USING ERRCODE = '40001';
  END IF;
  IF d.roster_lock_status <> 'open' THEN
    RAISE EXCEPTION 'ROSTER_LOCKED' USING ERRCODE = '40001';
  END IF;

  FOR pair IN SELECT value FROM jsonb_array_elements(p_pairs) LOOP
    IF jsonb_typeof(pair) IS DISTINCT FROM 'object'
      OR jsonb_typeof(pair->'members') IS DISTINCT FROM 'array'
      OR jsonb_array_length(pair->'members') <> 2 THEN
      RAISE EXCEPTION 'SETUP_PAYLOAD_INVALID' USING ERRCODE = '22023';
    END IF;
    ids := ARRAY[]::bigint[]; name := ''; first_club := NULL;
    FOR mem IN SELECT value FROM jsonb_array_elements(pair->'members') LOOP
      SELECT * INTO athlete FROM public.tournament_athletes
      WHERE id = (mem->>'tournament_athlete_id')::bigint
        AND group_id = p_group_id AND tournament_id = d.tournament_id FOR SHARE;
      IF NOT FOUND THEN RAISE EXCEPTION 'PAIR_ATHLETE_SCOPE_MISMATCH' USING ERRCODE = '23503'; END IF;
      IF athlete.id = ANY(ids) THEN RAISE EXCEPTION 'SETUP_PAYLOAD_INVALID' USING ERRCODE = '22023'; END IF;
      ids := array_append(ids, athlete.id);
      name := concat_ws(' / ', name, COALESCE(athlete.display_name_snapshot, 'VĐV #' || athlete.id));
      IF first_club IS NULL THEN first_club := athlete.tournament_club_id; END IF;
    END LOOP;

    INSERT INTO public.tournament_pairs(group_id, division_id, name_snapshot, pairing_mode, status)
    VALUES (p_group_id, p_division_id, name, p_pairing_mode, 'confirmed') RETURNING * INTO pair_row;
    FOR mem IN SELECT value FROM jsonb_array_elements(pair->'members') LOOP
      INSERT INTO public.tournament_pair_members(group_id, pair_id, tournament_athlete_id, role)
      VALUES (p_group_id, pair_row.id, (mem->>'tournament_athlete_id')::bigint,
        COALESCE(NULLIF(mem->>'role', ''), 'player'));
    END LOOP;
    INSERT INTO public.tournament_entries(group_id, division_id, tournament_club_id, pair_id, name_snapshot, status)
    VALUES (p_group_id, p_division_id, first_club, pair_row.id, name, 'approved') RETURNING * INTO entry_row;
    FOR mem IN SELECT value FROM jsonb_array_elements(pair->'members') LOOP
      SELECT * INTO athlete FROM public.tournament_athletes
      WHERE id = (mem->>'tournament_athlete_id')::bigint AND group_id = p_group_id;
      INSERT INTO public.tournament_entry_members(group_id, entry_id, athlete_id, display_name_snapshot, club_name_snapshot, skill_snapshot, roster_role)
      VALUES (p_group_id, entry_row.id, athlete.athlete_id,
        COALESCE(athlete.display_name_snapshot, 'VĐV #' || athlete.id), athlete.club_name_snapshot,
        athlete.phr_rating, COALESCE(NULLIF(mem->>'role', ''), 'player'));
    END LOOP;
    pair_count := pair_count + 1;
    pair_ids := pair_ids || jsonb_build_array(pair_row.id);
    entry_ids := entry_ids || jsonb_build_array(entry_row.id);
    created_pairs := created_pairs || jsonb_build_array(jsonb_build_object('pair_id', pair_row.id, 'entry_id', entry_row.id, 'member_ids', to_jsonb(ids)));
  END LOOP;

  UPDATE public.tournament_divisions
  SET setup_revision = setup_revision + 1, setup_updated_at = now()
  WHERE id = d.id AND group_id = p_group_id
  RETURNING setup_revision INTO d.setup_revision;

  result := jsonb_build_object('success', true, 'pairCount', pair_count, 'pairIds', pair_ids,
    'entryIds', entry_ids, 'pairs', created_pairs, 'setup_revision', d.setup_revision);
  INSERT INTO public.tournament_setup_mutations(group_id, operation, division_id, idempotency_key, payload_fingerprint, response)
  VALUES (p_group_id, 'confirm_tournament_pairs_revisioned', p_division_id, p_idempotency_key, payload_fingerprint, result);
  RETURN result;
END;
$$;

REVOKE ALL ON TABLE public.tournament_setup_mutations FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.confirm_tournament_pairs_revisioned(bigint,bigint,jsonb,text,bigint,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.confirm_tournament_pairs_revisioned(bigint,bigint,jsonb,text,bigint,text) TO service_role;

COMMENT ON FUNCTION public.confirm_tournament_pairs_revisioned(bigint,bigint,jsonb,text,bigint,text)
  IS 'Xác nhận pair/entry nguyên tử với CAS setup revision, roster lock và idempotency có scope/fingerprint.';
COMMENT ON CONSTRAINT tournament_entries_pair_id_fk ON public.tournament_entries
  IS 'Pair-backed entry không được orphan khi pair bị xoá.';

COMMIT;