-- Persist the division-specific identity roster and make setup locks authoritative.
-- Forward-only: divisions without roster rows keep legacy readiness semantics.
BEGIN;

CREATE TABLE IF NOT EXISTS public.tournament_division_roster_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES public.groups(id) ON DELETE CASCADE,
  division_id bigint NOT NULL REFERENCES public.tournament_divisions(id) ON DELETE CASCADE,
  tournament_athlete_id bigint NOT NULL REFERENCES public.tournament_athletes(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (group_id, division_id, tournament_athlete_id)
);
CREATE INDEX IF NOT EXISTS idx_tournament_division_roster_scope
  ON public.tournament_division_roster_members(group_id, division_id, tournament_athlete_id);
ALTER TABLE public.tournament_division_roster_members DISABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.assert_tournament_division_roster_member_scope()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM public.tournament_divisions d
    JOIN public.tournament_athletes a ON a.id = NEW.tournament_athlete_id
    WHERE d.id = NEW.division_id
      AND d.group_id = NEW.group_id
      AND a.group_id = NEW.group_id
      AND a.tournament_id = d.tournament_id
  ) THEN
    RAISE EXCEPTION 'DIVISION_ROSTER_ATHLETE_SCOPE_MISMATCH' USING ERRCODE = '23503';
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_tournament_division_roster_member_scope ON public.tournament_division_roster_members;
CREATE TRIGGER trg_tournament_division_roster_member_scope
  BEFORE INSERT OR UPDATE ON public.tournament_division_roster_members
  FOR EACH ROW EXECUTE FUNCTION public.assert_tournament_division_roster_member_scope();

CREATE OR REPLACE FUNCTION public.get_tournament_division_readiness(
  p_group_id bigint,
  p_tournament_id bigint,
  p_division_id bigint
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  d public.tournament_divisions%ROWTYPE;
  entry_count integer := 0;
  pair_count integer := 0;
  roster_count integer := 0;
  paired_athlete_count integer := 0;
  has_roster boolean := false;
  reasons jsonb := '[]'::jsonb;
BEGIN
  SELECT * INTO d FROM public.tournament_divisions
  WHERE id = p_division_id AND group_id = p_group_id AND tournament_id = p_tournament_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'division not found in tournament scope' USING ERRCODE = 'P0002'; END IF;

  SELECT EXISTS(SELECT 1 FROM public.tournament_division_roster_members r
    WHERE r.group_id = p_group_id AND r.division_id = p_division_id) INTO has_roster;
  IF has_roster THEN
    SELECT count(*)::integer INTO roster_count FROM public.tournament_division_roster_members r
    WHERE r.group_id = p_group_id AND r.division_id = p_division_id;
  ELSE
    SELECT count(*)::integer INTO roster_count FROM public.tournament_athletes a
    WHERE a.group_id = p_group_id AND a.tournament_id = p_tournament_id;
  END IF;
  SELECT count(*)::integer INTO entry_count FROM public.tournament_entries e
  WHERE e.group_id = p_group_id AND e.division_id = p_division_id AND e.status = 'approved';

  IF entry_count < 2 THEN reasons := reasons || jsonb_build_array(jsonb_build_object('code','ENTRY_COUNT_TOO_LOW','entity_id',p_division_id,'message','Cần ít nhất 2 entry đã duyệt để bốc thăm.')); END IF;
  IF has_roster AND roster_count = 0 THEN reasons := reasons || jsonb_build_array(jsonb_build_object('code','ROSTER_EMPTY','entity_id',p_division_id,'message','Danh sách vận động viên của nội dung đang trống.')); END IF;

  IF d.play_type = 'doubles' THEN
    SELECT count(*)::integer INTO pair_count FROM public.tournament_pairs p
    WHERE p.group_id = p_group_id AND p.division_id = p_division_id AND p.status IN ('confirmed','locked');
    SELECT count(DISTINCT pm.tournament_athlete_id)::integer INTO paired_athlete_count
    FROM public.tournament_pair_members pm JOIN public.tournament_pairs p ON p.id = pm.pair_id
    WHERE pm.group_id = p_group_id AND p.group_id = p_group_id AND p.division_id = p_division_id AND p.status IN ('confirmed','locked');

    SELECT COALESCE(jsonb_agg(reason ORDER BY reason->>'code', (reason->>'entity_id')::bigint), '[]'::jsonb) INTO reasons
    FROM (
      SELECT jsonb_build_object('code','PAIR_MEMBER_COUNT_INVALID','entity_id',p.id,'message','Mỗi cặp đã xác nhận phải có đúng 2 vận động viên.') reason
      FROM public.tournament_pairs p LEFT JOIN public.tournament_pair_members pm ON pm.pair_id=p.id AND pm.group_id=p_group_id
      WHERE p.group_id=p_group_id AND p.division_id=p_division_id AND p.status IN ('confirmed','locked') GROUP BY p.id HAVING count(pm.id)<>2
      UNION ALL
      SELECT jsonb_build_object('code','ATHLETE_IN_MULTIPLE_PAIRS','entity_id',pm.tournament_athlete_id,'message','Một vận động viên không được thuộc nhiều cặp trong cùng nội dung.')
      FROM public.tournament_pair_members pm JOIN public.tournament_pairs p ON p.id=pm.pair_id
      WHERE pm.group_id=p_group_id AND p.group_id=p_group_id AND p.division_id=p_division_id AND p.status IN ('confirmed','locked') GROUP BY pm.tournament_athlete_id HAVING count(DISTINCT pm.pair_id)>1
      UNION ALL
      SELECT jsonb_build_object('code','PAIR_ENTRY_LINK_MISSING','entity_id',p.id,'message','Cặp đã xác nhận chưa có entry liên kết trực tiếp.')
      FROM public.tournament_pairs p WHERE p.group_id=p_group_id AND p.division_id=p_division_id AND p.status IN ('confirmed','locked') AND NOT EXISTS (SELECT 1 FROM public.tournament_entries e WHERE e.group_id=p_group_id AND e.division_id=p_division_id AND e.pair_id=p.id AND e.status='approved')
      UNION ALL
      SELECT jsonb_build_object('code','APPROVED_DOUBLES_ENTRY_PAIR_ID_MISSING','entity_id',e.id,'message','Entry đôi đã duyệt phải liên kết trực tiếp với một cặp.')
      FROM public.tournament_entries e WHERE e.group_id=p_group_id AND e.division_id=p_division_id AND e.status='approved' AND e.pair_id IS NULL
      UNION ALL
      SELECT jsonb_build_object('code','PAIR_ENTRY_COUNT_MISMATCH','entity_id',p_division_id,'message','Số cặp đã xác nhận phải khớp chính xác số entry đôi đã duyệt.') WHERE pair_count<>entry_count
      UNION ALL
      SELECT jsonb_build_object('code','PAIR_MEMBER_NOT_IN_ROSTER','entity_id',pm.tournament_athlete_id,'message','Vận động viên trong cặp chưa thuộc roster của nội dung.')
      FROM public.tournament_pair_members pm JOIN public.tournament_pairs p ON p.id=pm.pair_id
      WHERE has_roster AND pm.group_id=p_group_id AND p.group_id=p_group_id AND p.division_id=p_division_id AND p.status IN ('confirmed','locked')
        AND NOT EXISTS (SELECT 1 FROM public.tournament_division_roster_members r WHERE r.group_id=p_group_id AND r.division_id=p_division_id AND r.tournament_athlete_id=pm.tournament_athlete_id)
      UNION ALL
      SELECT jsonb_build_object('code','ROSTER_ATHLETE_UNPAIRED','entity_id',r.tournament_athlete_id,'message','Vận động viên đã chọn chưa được ghép cặp.')
      FROM public.tournament_division_roster_members r WHERE has_roster AND r.group_id=p_group_id AND r.division_id=p_division_id
        AND NOT EXISTS (SELECT 1 FROM public.tournament_pair_members pm JOIN public.tournament_pairs p ON p.id=pm.pair_id WHERE pm.group_id=p_group_id AND pm.tournament_athlete_id=r.tournament_athlete_id AND p.group_id=p_group_id AND p.division_id=p_division_id AND p.status IN ('confirmed','locked'))
    ) q;
    IF entry_count < 2 THEN reasons := reasons || jsonb_build_array(jsonb_build_object('code','ENTRY_COUNT_TOO_LOW','entity_id',p_division_id,'message','Cần ít nhất 2 entry đã duyệt để bốc thăm.')); END IF;
    IF has_roster AND roster_count = 0 THEN reasons := reasons || jsonb_build_array(jsonb_build_object('code','ROSTER_EMPTY','entity_id',p_division_id,'message','Danh sách vận động viên của nội dung đang trống.')); END IF;
  END IF;

  RETURN jsonb_build_object('division_id',d.id,'tournament_id',d.tournament_id,'revision',d.setup_revision,
    'roster_lock_status',d.roster_lock_status,'roster_locked_at',d.roster_locked_at,'roster_locked_by',d.roster_locked_by,
    'status',CASE WHEN jsonb_array_length(reasons)>0 THEN 'blocked' ELSE 'ready' END,'reasons',reasons,
    'counts',jsonb_build_object('roster',roster_count,'pairs',pair_count,'entries',entry_count,'paired_athletes',paired_athlete_count,'unpaired',GREATEST(roster_count-paired_athlete_count,0)),
    'roster_source',CASE WHEN has_roster THEN 'division_aggregate' ELSE 'legacy_tournament_scope' END,'legacy_compatible',true);
END;
$$;

CREATE OR REPLACE FUNCTION public.finalize_tournament_draw(
  p_group_id bigint, p_stage_id bigint, p_expected_config jsonb,
  p_matches jsonb, p_idempotency_key text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE s public.tournament_stages%ROWTYPE; slot jsonb; slots jsonb; result jsonb; locked_draw jsonb; readiness jsonb;
BEGIN
  IF p_idempotency_key IS NULL OR length(trim(p_idempotency_key)) NOT BETWEEN 1 AND 200 THEN RAISE EXCEPTION 'INVALID_IDEMPOTENCY_KEY' USING ERRCODE='22023'; END IF;
  SELECT * INTO s FROM public.tournament_stages WHERE id=p_stage_id AND group_id=p_group_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'STAGE_NOT_FOUND' USING ERRCODE='P0002'; END IF;
  IF s.config->'draw'->>'status'='locked' AND s.config->'draw'->>'finalize_key'=p_idempotency_key THEN RETURN s.config->'draw'->'finalize_result'; END IF;
  IF s.config IS DISTINCT FROM p_expected_config OR s.config->'draw'->>'status' IS DISTINCT FROM 'draft' THEN RAISE EXCEPTION 'DRAW_CONFLICT' USING ERRCODE='40001'; END IF;
  IF s.division_id IS NOT NULL THEN
    readiness:=public.get_tournament_division_readiness(p_group_id,s.tournament_id,s.division_id);
    IF readiness->>'status'<>'ready' THEN RAISE EXCEPTION 'SETUP_NOT_READY' USING ERRCODE='40001'; END IF;
  END IF;
  LOCK TABLE public.tournament_matches IN SHARE ROW EXCLUSIVE MODE;
  IF EXISTS (SELECT 1 FROM public.tournament_matches WHERE group_id=p_group_id AND stage_id=p_stage_id) THEN RAISE EXCEPTION 'DRAW_HAS_EXISTING_MATCHES' USING ERRCODE='40001'; END IF;
  slots:=s.config->'draw'->'slots';
  IF jsonb_typeof(slots) IS DISTINCT FROM 'array' OR jsonb_array_length(slots)<2 OR EXISTS (SELECT 1 FROM jsonb_array_elements(slots) x GROUP BY x->>'entry_id' HAVING count(*)>1 OR x->>'entry_id' IS NULL) THEN RAISE EXCEPTION 'DRAW_INVALID_SLOTS' USING ERRCODE='22023'; END IF;
  IF s.division_id IS NOT NULL THEN
    IF EXISTS (SELECT 1 FROM jsonb_array_elements(slots) x WHERE NOT EXISTS (SELECT 1 FROM public.tournament_entries e WHERE e.id=(x->>'entry_id')::bigint AND e.group_id=p_group_id AND e.division_id=s.division_id AND e.status='approved'))
      OR jsonb_array_length(slots)<>(SELECT count(*) FROM public.tournament_entries WHERE group_id=p_group_id AND division_id=s.division_id AND status='approved') THEN RAISE EXCEPTION 'DRAW_MEMBERSHIP_CHANGED' USING ERRCODE='40001'; END IF;
  ELSIF EXISTS (SELECT 1 FROM jsonb_array_elements(slots) x WHERE NOT EXISTS (SELECT 1 FROM public.tournament_entrants e WHERE e.id=(x->>'entry_id')::bigint AND e.group_id=p_group_id AND e.tournament_id=s.tournament_id)) THEN RAISE EXCEPTION 'DRAW_MEMBERSHIP_CHANGED' USING ERRCODE='40001'; END IF;
  DELETE FROM public.tournament_stage_entrants WHERE group_id=p_group_id AND stage_id=p_stage_id;
  FOR slot IN SELECT value FROM jsonb_array_elements(slots) LOOP
    INSERT INTO public.tournament_stage_entrants(group_id,stage_id,division_id,entry_id,entrant_id,group_label,seed_in_stage)
    VALUES(p_group_id,p_stage_id,s.division_id,CASE WHEN s.division_id IS NOT NULL THEN (slot->>'entry_id')::bigint END,CASE WHEN s.division_id IS NULL THEN (slot->>'entry_id')::bigint END,slot->>'group_label',(slot->>'seed_in_stage')::integer);
  END LOOP;
  IF s.division_id IS NOT NULL THEN result:=public.replace_tournament_entry_schedule(p_group_id,p_stage_id,p_matches,NULL); ELSE result:=public.replace_tournament_schedule(p_group_id,p_stage_id,p_matches,NULL); END IF;
  locked_draw:=(s.config->'draw') || jsonb_build_object('status','locked','locked_at',now(),'finalize_key',p_idempotency_key);
  result:=result || jsonb_build_object('draw',locked_draw);
  UPDATE public.tournament_stages SET config=jsonb_set(s.config,'{draw}',locked_draw || jsonb_build_object('finalize_result',result)) WHERE id=s.id AND group_id=p_group_id;
  RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION public.replace_tournament_division_roster_revisioned(
  p_group_id bigint, p_tournament_id bigint, p_division_id bigint, p_athlete_ids jsonb,
  p_expected_setup_revision bigint, p_idempotency_key text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE d public.tournament_divisions%ROWTYPE; cached public.tournament_setup_mutations%ROWTYPE; fingerprint text; normalized_ids bigint[]; result jsonb;
BEGIN
  IF p_expected_setup_revision IS NULL OR p_expected_setup_revision < 1 THEN RAISE EXCEPTION 'SETUP_REVISION_CONFLICT' USING ERRCODE='40001'; END IF;
  IF p_idempotency_key IS NULL OR length(btrim(p_idempotency_key)) NOT BETWEEN 1 AND 200 OR jsonb_typeof(p_athlete_ids) IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'SETUP_PAYLOAD_INVALID' USING ERRCODE='22023'; END IF;
  SELECT array_agg(DISTINCT value::text::bigint ORDER BY value::text::bigint) INTO normalized_ids FROM jsonb_array_elements_text(p_athlete_ids);
  IF COALESCE(array_length(normalized_ids,1),0) <> jsonb_array_length(p_athlete_ids) THEN RAISE EXCEPTION 'SETUP_PAYLOAD_INVALID' USING ERRCODE='22023'; END IF;
  fingerprint := md5(jsonb_build_object('division_id',p_division_id,'athlete_ids',COALESCE(to_jsonb(normalized_ids),'[]'::jsonb))::text);
  PERFORM pg_advisory_xact_lock(hashtextextended(p_group_id::text||':division-roster:'||p_idempotency_key,0));
  SELECT * INTO cached FROM public.tournament_setup_mutations WHERE group_id=p_group_id AND operation='replace_tournament_division_roster_revisioned' AND idempotency_key=p_idempotency_key FOR UPDATE;
  IF FOUND THEN IF cached.division_id<>p_division_id OR cached.payload_fingerprint<>fingerprint THEN RAISE EXCEPTION 'IDEMPOTENCY_KEY_REUSED' USING ERRCODE='22023'; END IF; RETURN cached.response; END IF;
  SELECT * INTO d FROM public.tournament_divisions WHERE id=p_division_id AND group_id=p_group_id AND tournament_id=p_tournament_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'division not found in tournament scope' USING ERRCODE='P0002'; END IF;
  IF d.setup_revision<>p_expected_setup_revision THEN RAISE EXCEPTION 'SETUP_REVISION_CONFLICT' USING ERRCODE='40001'; END IF;
  IF d.roster_lock_status<>'open' THEN RAISE EXCEPTION 'ROSTER_LOCKED' USING ERRCODE='40001'; END IF;
  IF EXISTS (SELECT 1 FROM unnest(COALESCE(normalized_ids,'{}'::bigint[])) id WHERE NOT EXISTS (SELECT 1 FROM public.tournament_athletes a WHERE a.id=id AND a.group_id=p_group_id AND a.tournament_id=p_tournament_id)) THEN RAISE EXCEPTION 'DIVISION_ROSTER_ATHLETE_SCOPE_MISMATCH' USING ERRCODE='23503'; END IF;
  IF EXISTS (SELECT 1 FROM public.tournament_division_roster_members r WHERE r.group_id=p_group_id AND r.division_id=p_division_id AND NOT r.tournament_athlete_id=ANY(COALESCE(normalized_ids,'{}'::bigint[]))) OR EXISTS (SELECT 1 FROM unnest(COALESCE(normalized_ids,'{}'::bigint[])) id WHERE NOT EXISTS (SELECT 1 FROM public.tournament_division_roster_members r WHERE r.group_id=p_group_id AND r.division_id=p_division_id AND r.tournament_athlete_id=id)) THEN
    DELETE FROM public.tournament_division_roster_members WHERE group_id=p_group_id AND division_id=p_division_id;
    INSERT INTO public.tournament_division_roster_members(group_id,division_id,tournament_athlete_id) SELECT p_group_id,p_division_id,id FROM unnest(COALESCE(normalized_ids,'{}'::bigint[])) id;
    UPDATE public.tournament_divisions SET setup_revision=setup_revision+1,setup_updated_at=now() WHERE id=d.id AND group_id=p_group_id RETURNING setup_revision INTO d.setup_revision;
  END IF;
  result := jsonb_build_object('success',true,'setup_revision',d.setup_revision,'athlete_ids',COALESCE(to_jsonb(normalized_ids),'[]'::jsonb),'readiness',public.get_tournament_division_readiness(p_group_id,p_tournament_id,p_division_id));
  INSERT INTO public.tournament_setup_mutations(group_id,operation,division_id,idempotency_key,payload_fingerprint,response) VALUES(p_group_id,'replace_tournament_division_roster_revisioned',p_division_id,p_idempotency_key,fingerprint,result);
  RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_tournament_division_roster_lock_revisioned(
  p_group_id bigint, p_tournament_id bigint, p_division_id bigint, p_lock boolean, p_actor text,
  p_reason text, p_expected_setup_revision bigint, p_idempotency_key text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE d public.tournament_divisions%ROWTYPE; cached public.tournament_setup_mutations%ROWTYPE; readiness jsonb; fingerprint text; result jsonb;
BEGIN
  IF p_expected_setup_revision IS NULL OR p_expected_setup_revision<1 THEN RAISE EXCEPTION 'SETUP_REVISION_CONFLICT' USING ERRCODE='40001'; END IF;
  IF p_idempotency_key IS NULL OR length(btrim(p_idempotency_key)) NOT BETWEEN 1 AND 200 THEN RAISE EXCEPTION 'SETUP_PAYLOAD_INVALID' USING ERRCODE='22023'; END IF;
  IF NOT p_lock AND nullif(btrim(coalesce(p_reason,'')),'') IS NULL THEN RAISE EXCEPTION 'REASON_REQUIRED' USING ERRCODE='22023'; END IF;
  fingerprint:=md5(jsonb_build_object('division_id',p_division_id,'lock',p_lock,'reason',nullif(btrim(coalesce(p_reason,'')),''))::text);
  PERFORM pg_advisory_xact_lock(hashtextextended(p_group_id::text||':division-roster-lock:'||p_idempotency_key,0));
  SELECT * INTO cached FROM public.tournament_setup_mutations WHERE group_id=p_group_id AND operation='set_tournament_division_roster_lock_revisioned' AND idempotency_key=p_idempotency_key FOR UPDATE;
  IF FOUND THEN IF cached.division_id<>p_division_id OR cached.payload_fingerprint<>fingerprint THEN RAISE EXCEPTION 'IDEMPOTENCY_KEY_REUSED' USING ERRCODE='22023'; END IF; RETURN cached.response; END IF;
  SELECT * INTO d FROM public.tournament_divisions WHERE id=p_division_id AND group_id=p_group_id AND tournament_id=p_tournament_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'division not found in tournament scope' USING ERRCODE='P0002'; END IF;
  IF d.setup_revision<>p_expected_setup_revision THEN RAISE EXCEPTION 'SETUP_REVISION_CONFLICT' USING ERRCODE='40001'; END IF;
  IF p_lock THEN
    readiness:=public.get_tournament_division_readiness(p_group_id,p_tournament_id,p_division_id);
    IF readiness->>'status'<>'ready' THEN RAISE EXCEPTION 'SETUP_NOT_READY' USING ERRCODE='40001'; END IF;
    IF d.roster_lock_status='open' THEN UPDATE public.tournament_divisions SET roster_lock_status='locked',roster_locked_at=now(),roster_locked_by=nullif(btrim(p_actor),''),setup_revision=setup_revision+1,setup_updated_at=now() WHERE id=d.id AND group_id=p_group_id RETURNING setup_revision INTO d.setup_revision; END IF;
  ELSE
    IF EXISTS (SELECT 1 FROM public.tournament_stages s WHERE s.group_id=p_group_id AND s.tournament_id=p_tournament_id AND s.division_id=p_division_id AND (s.config->'draw'->>'status'='locked' OR EXISTS (SELECT 1 FROM public.tournament_matches m WHERE m.group_id=p_group_id AND m.stage_id=s.id))) THEN RAISE EXCEPTION 'ROSTER_UNLOCK_BLOCKED' USING ERRCODE='40001'; END IF;
    IF d.roster_lock_status='locked' THEN UPDATE public.tournament_divisions SET roster_lock_status='open',roster_locked_at=NULL,roster_locked_by=NULL,setup_revision=setup_revision+1,setup_updated_at=now() WHERE id=d.id AND group_id=p_group_id RETURNING setup_revision INTO d.setup_revision; END IF;
  END IF;
  readiness:=public.get_tournament_division_readiness(p_group_id,p_tournament_id,p_division_id);
  result:=jsonb_build_object('success',true,'setup_revision',d.setup_revision,'roster_lock_status',CASE WHEN p_lock THEN 'locked' ELSE 'open' END,'readiness',readiness);
  INSERT INTO public.tournament_setup_mutations(group_id,operation,division_id,idempotency_key,payload_fingerprint,response) VALUES(p_group_id,'set_tournament_division_roster_lock_revisioned',p_division_id,p_idempotency_key,fingerprint,result);
  RETURN result;
END;
$$;

REVOKE ALL ON TABLE public.tournament_division_roster_members FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_tournament_division_readiness(bigint,bigint,bigint) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.finalize_tournament_draw(bigint,bigint,jsonb,jsonb,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.replace_tournament_division_roster_revisioned(bigint,bigint,bigint,jsonb,bigint,text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.set_tournament_division_roster_lock_revisioned(bigint,bigint,bigint,boolean,text,text,bigint,text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_tournament_division_readiness(bigint,bigint,bigint) TO service_role;
GRANT EXECUTE ON FUNCTION public.finalize_tournament_draw(bigint,bigint,jsonb,jsonb,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.replace_tournament_division_roster_revisioned(bigint,bigint,bigint,jsonb,bigint,text) TO service_role;
GRANT EXECUTE ON FUNCTION public.set_tournament_division_roster_lock_revisioned(bigint,bigint,bigint,boolean,text,text,bigint,text) TO service_role;
COMMENT ON TABLE public.tournament_division_roster_members IS 'Roster identity được chọn riêng cho từng nội dung thi đấu.';
COMMIT;
