const fs = require('fs'); const path = require('path');
const root = path.join(__dirname, '..', '..');
const read = (f) => fs.readFileSync(path.join(root, f), 'utf8');
const exists = (f) => fs.existsSync(path.join(root, f));
const assert = (c, m) => { if (!c) { console.error(`FAIL: ${m}`); process.exit(1); } };
const f = 'app/api/tournament-v2/tournaments/route.js';
assert(exists(f), 'route tồn tại');
const s = read(f);
assert(s.includes('requireValidatedGroupAdmin'), 'có database-backed admin guard');
assert(/export async function POST/.test(s) && /export async function PATCH/.test(s) && /export async function DELETE/.test(s) && /export async function GET/.test(s), 'đủ 4 method');
assert(s.includes('entrant_type') && s.includes('public_slug'), 'hỗ trợ entrant_type + server slug');
assert(s.includes('visibility') && s.includes('Invalid tournament visibility'), 'validate visibility');
assert(s.includes('randomBytes') && !s.includes('body.public_slug'), 'slug do server tạo, không nhận tùy ý từ client');
assert(s.includes(".eq('group_id'"), 'scope group_id');
assert(!/\.eq\('id',\s*1\)/.test(s) && !s.includes('tournament_id = 1'), 'không hardcode id');
assert(s.includes('tournaments'), 'thao tác bảng tournaments');
assert(!/status:\s*body\.status\s*\|\|\s*'draft'/.test(s) && /status:\s*'draft'/.test(s), 'POST ép trạng thái draft');
assert(/from '@\/lib\/tournament\/lifecycle'/.test(s) && /canTransition\(/.test(s), 'PATCH kiểm lifecycle');
assert(/INVALID_STATUS_TRANSITION/.test(s) && /TOURNAMENT_HAS_APPROVED_REGISTRATIONS/.test(s), 'PATCH trả lỗi rõ ràng');
assert(/canDelete\(/.test(s), 'DELETE gọi canDelete');
assert(/groupOf\(/.test(s) && /match_progress/.test(s), 'GET trả nhóm và tiến độ');
assert(/tournament_divisions/.test(s) && /registration_capacity/.test(s), 'GET tổng hợp sức chứa từng nội dung');
assert(/tournament_registrations/.test(s) && /registration_summary/.test(s), 'GET trả số đăng ký đã duyệt theo giải');
assert(/organizer_mode/.test(s) && /formats/.test(s), 'GET trả phạm vi tổ chức và thể thức để render danh sách');
assert(/finalStandingsFrom/.test(s), 'chốt giải ghim hạng chung cuộc');
assert(/final_standings/.test(s), 'ghi vào cột final_standings');
console.log('api-tournaments contract ok');
