const fs = require('fs'); const path = require('path');
const root = path.join(__dirname, '..', '..');
const read = (f) => fs.readFileSync(path.join(root, f), 'utf8');
const exists = (f) => fs.existsSync(path.join(root, f));
const assert = (c, m) => { if (!c) { console.error(`FAIL: ${m}`); process.exit(1); } };
const f = 'app/api/tournament-v2/generate/route.js';
assert(exists(f), 'route tồn tại');
const s = read(f);
assert(s.includes('requireValidatedGroupAdmin'), 'database-backed admin guard');
assert(s.includes('getScheduleEngine') && s.includes('generateSchedule'), 'gọi schedule engine');
assert(s.includes('scheduleToInsertRows'), 'dùng persistence helper để chuẩn hóa payload');
assert(s.includes('_parent_key') && s.includes('parent_slot'), 'gửi liên kết parent theo khóa schedule');
assert(s.includes('stageId') && s.includes("p_group_id: groupId"), 'RPC nhận đúng tenant + stage scope');
assert(s.includes("rpc('replace_tournament_schedule'"), 'regenerate schedule qua database transaction RPC');
console.log('api-generate contract ok');
