const fs = require('fs');
const path = require('path');
const source = fs.readFileSync(path.join(__dirname, '..', '..', 'app', 'giai-dau', 'v2', 'console', 'TournamentConsoleV2.js'), 'utf8');
const shell = fs.readFileSync(path.join(__dirname, '..', '..', 'app', 'giai-dau', 'v2', 'console', 'ConsoleShell.js'), 'utf8');
const fullPage = path.join(__dirname, '..', '..', 'app', 'dieu-hanh-giai', '[tournamentId]', 'page.js');
const dashboardPage = path.join(__dirname, '..', '..', 'app', 'giai-dau', 'v2', 'TournamentV2DashboardClient.js');
const assert = (condition, message) => { if (!condition) { console.error(`FAIL: ${message}`); process.exit(1); } };
assert(/ConsoleShell/.test(source), 'console dùng shell sidebar');
assert(!/v2-tabbar/.test(source), 'không còn thanh 7 tab ngang');
for (const tab of ['SettingsTab', 'TeamsTab', 'ResultsTab', 'StandingsTab', 'BracketTab', 'OpenRegTab']) assert(new RegExp(tab).test(source), `${tab} được dùng lại`);
assert(/CourtsStep|ControlStep|LogStep/.test(source), 'mount ba màn mới');
assert(/readiness/.test(source), 'có readiness');
assert(fs.existsSync(fullPage), 'có route điều hành toàn màn hình độc lập AppShell');
const fullSource = fs.readFileSync(fullPage, 'utf8');
assert(/TournamentConsoleV2/.test(fullSource), 'route toàn màn hình tái dùng console thật');
assert(/requireTournamentAccess/.test(fullSource) && /need:\s*'write'/.test(fullSource) && /redirect\(/.test(fullSource), 'gõ URL trực tiếp phải qua server-side tournament admin guard');
assert(/\/dieu-hanh-giai\//.test(fs.readFileSync(dashboardPage, 'utf8')), 'CTA danh sách điều hướng sang route toàn màn hình');
assert(/api\/groups\/session/.test(source) && /actor=\{session\}/.test(source), 'console lấy admin thực từ session server');
assert(/ops-admin-card/.test(shell) && /actor/.test(shell), 'menu trái có thẻ thông tin admin');
console.log('ui-console contract ok');
