const fs = require('fs');
const path = require('path');
const source = fs.readFileSync(path.join(__dirname, '..', '..', 'app', 'giai-dau', 'v2', 'console', 'steps', 'ControlStep.js'), 'utf8');
const assert = (condition, message) => { if (!condition) { console.error(`FAIL: ${message}`); process.exit(1); } };
assert(/transitionMatch/.test(source) && /matchElapsed/.test(source), 'đổi trạng thái và đồng hồ');
for (const label of ['Gọi vào sân', 'Bắt đầu đấu', 'Tạm dừng']) assert(source.includes(label), `có nút ${label}`);
assert(/mic|Thẻ đọc|đọc mic/.test(source), 'thẻ đọc mic');
assert(!/speechSynthesis|SpeechSynthesis|DUPR|Live Stream|livestream/i.test(source), 'không có tính năng ngoài phạm vi');
assert(/Thời lượng trận trung bình|trung bình/.test(source), 'số liệu thật');
assert(!/#[0-9a-fA-F]{6}/.test(source), 'không hardcode màu');
console.log('ui-control-step contract ok');