const fs = require('fs');
const path = require('path');
const source = fs.readFileSync(path.join(__dirname, '..', '..', 'app', 'giai-dau', 'v2', 'console', 'TournamentConsoleV2.js'), 'utf8');
const assert = (condition, message) => { if (!condition) { console.error(`FAIL: ${message}`); process.exit(1); } };
assert(/ConsoleShell/.test(source), 'console dùng shell sidebar');
assert(!/v2-tabbar/.test(source), 'không còn thanh 7 tab ngang');
for (const tab of ['SettingsTab', 'TeamsTab', 'ResultsTab', 'StandingsTab', 'BracketTab', 'OpenRegTab']) assert(new RegExp(tab).test(source), `${tab} được dùng lại`);
assert(/CourtsStep|ControlStep|LogStep/.test(source), 'mount ba màn mới');
assert(/readiness/.test(source), 'có readiness');
console.log('ui-console contract ok');
