const fs = require('fs'); const path = require('path');
const root = path.join(__dirname, '..', '..');
const read = (f) => fs.readFileSync(path.join(root, f), 'utf8');
const exists = (f) => fs.existsSync(path.join(root, f));
const assert = (c, m) => { if (!c) { console.error(`FAIL: ${m}`); process.exit(1); } };
const f = 'app/giai-dau/v2/page.js';
assert(exists(f), 'trang list tồn tại');
const s = read(f);
assert(/getValidatedGroupSessionFromCookies/.test(s), 'route danh sách xác thực phiên CLB từ server');
assert(/redirect\('\/truy-cap-bi-tu-choi'\)/.test(s), 'khách được chuyển tới màn hình từ chối truy cập');
assert(exists('app/giai-dau/v2/TournamentV2DashboardClient.js'), 'dashboard client được tách sau server guard');
const dashboard = read('app/giai-dau/v2/TournamentV2DashboardClient.js');
assert(dashboard.includes("'use client'") || dashboard.includes('"use client"'), 'dashboard là client component');
assert(dashboard.includes('listTournaments') && dashboard.includes('tournamentV2Client'), 'dashboard dùng client wrapper');
assert(dashboard.includes("fetch('/api/groups/session'"), 'dashboard lấy role từ phiên hiện tại');
assert(dashboard.includes("sessionView?.session?.role === 'admin'"), 'dashboard hiển thị thao tác theo vai trò admin thực tế');
assert(!dashboard.includes('getCurrentGroupClient'), 'không lấy quyền admin từ localStorage');
assert(exists('app/truy-cap-bi-tu-choi/page.js'), 'có màn hình giải thích quyền truy cập');
const denied = read('app/truy-cap-bi-tu-choi/page.js');
assert(/chỉ có thể xem trang chi tiết.*giải cộng đồng/i.test(denied), 'màn hình nêu rõ khách chỉ xem được chi tiết giải cộng đồng');
assert(!read('app/giai-dau/v2/[slug]/page.js').includes('getValidatedGroupSessionFromCookies'), 'trang chi tiết giải công khai không bị chặn bởi dashboard guard');
assert(/Tạo|Thêm/.test(dashboard), 'có nút tạo (tiếng Việt)');
assert(exists('app/giai-dau/v2/v2.css'), 'css kèm');
assert(/Đang diễn ra/.test(dashboard) && /Sắp tổ chức/.test(dashboard) && /Đã kết thúc/.test(dashboard), 'ba nhóm vòng đời');
assert(/sortForGroup|groupOf/.test(dashboard) && /tournament\/lifecycle/.test(dashboard), 'nhóm bằng lifecycle');
assert(/placeholder="Tìm/.test(dashboard), 'có ô tìm');
assert(/STATUS_LABELS/.test(dashboard), 'nhãn trạng thái lấy từ lifecycle');
assert(!/active:\s*'Đang diễn ra'/.test(dashboard), 'không còn active');
assert(/match_progress/.test(dashboard), 'hiện tiến độ trận');
assert(/v2-dashboard-header/.test(dashboard), 'dashboard admin có phần đầu điều hành');
assert(/v2-stat-grid/.test(dashboard), 'dashboard admin có các thẻ thống kê');
assert(/v2-status-filter/.test(dashboard), 'dashboard admin có bộ lọc theo trạng thái');
assert(/v2-tournament-row/.test(dashboard), 'danh sách giải dùng hàng điều hành ngang theo mockup');
assert(/v2-tournament-visual/.test(dashboard), 'mỗi hàng giải có khối hình minh hoạ');
assert(/v2-tournament-actions/.test(dashboard), 'mỗi hàng giải có cụm thao tác admin');
assert(/registration_summary/.test(dashboard), 'hiển thị quy mô và đăng ký từ summary API');
assert(/organizer_mode/.test(dashboard), 'hiển thị phạm vi tổ chức');
assert(/v2-tournament-tags/.test(dashboard), 'hiển thị thẻ phạm vi và thể thức');
assert(/v2-stat-grid/.test(read('app/giai-dau/v2/v2.css')), 'có CSS cho dashboard admin');
assert(/v2-tournament-row/.test(read('app/giai-dau/v2/v2.css')), 'có CSS cho hàng danh sách giải');
assert(/v2-tournament-tags/.test(read('app/giai-dau/v2/v2.css')), 'có CSS cho thẻ phạm vi và thể thức');
console.log('ui-list contract ok');
