const fs = require('fs'); const path = require('path');
const root = path.join(__dirname, '..', '..');
const read = (f) => fs.readFileSync(path.join(root, f), 'utf8');
const exists = (f) => fs.existsSync(path.join(root, f));
const assert = (c, m) => { if (!c) { console.error(`FAIL: ${m}`); process.exit(1); } };
const f = 'app/giai-dau/v2/[slug]/page.js';
assert(exists(f), 'trang công khai tồn tại');
const s = read(f);
assert(s.includes('getPublic') || s.includes('/api/tournament-v2/public'), 'load dữ liệu công khai');
assert(!s.includes('supabaseClient') && !s.includes("from '@/lib/supabaseClient'"), 'không đọc Supabase trực tiếp trên browser');
assert(!s.includes('.channel(') && !s.includes('postgres_changes'), 'không subscribe realtime broad channel');
assert(s.includes('nextPollingDelay'), 'polling adaptive có backoff');
assert(s.includes('standingsByStage') && s.includes('gamesByMatchId'), 'dùng standings/game từ snapshot');
assert(s.includes('err.status === 404') && s.includes('setData(null)'), 'xóa snapshot stale khi link bị thu hồi');
console.log('ui-public contract ok');
