const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..', '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const assert = (condition, message) => { if (!condition) { console.error(`FAIL: ${message}`); process.exit(1); } };
const css = read('app/giai-dau/v2/console/shell.css');
assert(/Montserrat/.test(css), 'font Montserrat');
assert(!/Outfit/.test(css), 'không dùng Outfit');
for (const token of ['--court-green', '--pickle-lime', '--surface-court', '--live-cyan', '--rally-coral']) assert(!css.includes(token), `không dùng ${token}`);
assert(/--ops-bg/.test(css) && /--ops-indigo/.test(css), 'có token tối và tím');
assert(/prefers-reduced-motion/.test(css), 'tôn trọng reduced motion');
const shell = read('app/giai-dau/v2/console/ConsoleShell.js');
assert(/'use client'|"use client"/.test(shell), 'client component');
for (const label of ['Cấu hình giải', 'Sân & sơ đồ', 'VĐV & cặp đấu', 'Bốc thăm', 'Trung tâm điều hành', 'Lịch thi đấu', 'Bảng đấu', 'Nhật ký']) assert(shell.includes(label), `sidebar có ${label}`);
assert(/LIVE/.test(shell) && /step=/.test(shell) && /LEGACY_TAB_TO_STEP|tabParam/.test(shell) && /drawer/.test(shell), 'điều hướng và drawer');
const logStep = read('app/giai-dau/v2/console/steps/LogStep.js');
assert(/listOperationLogs/.test(logStep), 'LogStep đọc nhật ký qua client wrapper');
assert(/Trước → Sau|Trước|Sau/.test(logStep), 'LogStep có cột trước/sau');
assert(/Lý do/.test(logStep), 'LogStep có cột lý do');
assert(!/xoá|Xoá|delete/i.test(logStep), 'LogStep chỉ đọc');
console.log('ui-shell contract ok');